import type { Tier } from "../profiles";
import type { Domain } from "../domains";
import type { StrategyId } from "../strategies";
import { shuffle } from "../shuffle";

export type LocalizedText = { fr: string; en: string };

export type Problem = {
  id: string;
  tier: Tier;
  domain: Domain;
  prompt: LocalizedText;
  options: LocalizedText[];
  correctIndex: number;
  hint: LocalizedText;
  strategyId: StrategyId;
  explanation: LocalizedText;
};

export const PROBLEMS: Problem[] = [
  // ===== ECLAIREUR (6 ans) =====

  // Logique
  {
    id: "ecl-log-1",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Rouge, Bleu, Rouge, Bleu, Rouge, ... Quelle est la couleur suivante ?", en: "Red, Blue, Red, Blue, Red, ... What color comes next?" },
    options: [
      { fr: "Bleu", en: "Blue" },
      { fr: "Rouge", en: "Red" },
      { fr: "Vert", en: "Green" },
    ],
    correctIndex: 0,
    hint: { fr: "Regarde comment les couleurs alternent, une par une.", en: "Look at how the colors alternate, one by one." },
    strategyId: "chercher-motif",
    explanation: { fr: "Les couleurs alternent : Rouge, Bleu, Rouge, Bleu... Après Rouge vient toujours Bleu.", en: "The colors alternate: Red, Blue, Red, Blue... After Red always comes Blue." },
  },
  {
    id: "ecl-log-2",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Regarde cette suite de formes : 🔺 🔺 🔷 🔺. Laquelle est différente des autres ?", en: "Look at this sequence of shapes: 🔺 🔺 🔷 🔺. Which one is different from the others?" },
    options: [
      { fr: "La 1ère", en: "The 1st" },
      { fr: "La 2ème", en: "The 2nd" },
      { fr: "La 3ème", en: "The 3rd" },
    ],
    correctIndex: 2,
    hint: { fr: "Compare chaque forme aux autres, une par une.", en: "Compare each shape to the others, one by one." },
    strategyId: "dessiner",
    explanation: { fr: "Les 1ère, 2ème et 4ème formes sont des triangles. La 3ème est un losange : c'est elle qui est différente.", en: "The 1st, 2nd and 4th shapes are triangles. The 3rd is a diamond: that's the different one." },
  },
  {
    id: "ecl-log-3",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Léo a plus de billes que Zoé. Zoé a plus de billes que Tom. Qui a le moins de billes ?", en: "Léo has more marbles than Zoé. Zoé has more marbles than Tom. Who has the fewest marbles?" },
    options: [
      { fr: "Tom", en: "Tom" },
      { fr: "Zoé", en: "Zoé" },
      { fr: "Léo", en: "Léo" },
    ],
    correctIndex: 0,
    hint: { fr: "Range les trois amis du plus petit nombre de billes au plus grand.", en: "Sort the three friends from the fewest marbles to the most." },
    strategyId: "dessiner",
    explanation: { fr: "Léo a plus que Zoé, et Zoé a plus que Tom. Dans l'ordre : Tom, puis Zoé, puis Léo. Tom en a donc le moins.", en: "Léo has more than Zoé, and Zoé has more than Tom. In order: Tom, then Zoé, then Léo. So Tom has the fewest." },
  },
  {
    id: "ecl-log-4",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Un motif se répète : ⭐️ ⭐️ 🌙 ⭐️ ⭐️ 🌙 ... Quel symbole est le 6ème ?", en: "A pattern repeats: ⭐️ ⭐️ 🌙 ⭐️ ⭐️ 🌙 ... What is the 6th symbol?" },
    options: [
      { fr: "⭐️", en: "⭐️" },
      { fr: "🌙", en: "🌙" },
      { fr: "❓", en: "❓" },
    ],
    correctIndex: 1,
    hint: { fr: "Le motif se répète toutes les 3 cases : compte par groupes de 3.", en: "The pattern repeats every 3 spots: count in groups of 3." },
    strategyId: "chercher-motif",
    explanation: { fr: "Le motif ⭐️⭐️🌙 fait 3 symboles. La 6ème case termine le 2ème groupe de 3 : c'est donc 🌙.", en: "The pattern ⭐️⭐️🌙 is 3 symbols long. Spot 6 ends the 2nd group of 3: so it's 🌙." },
  },

  // Calcul
  {
    id: "ecl-cal-1",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Combien font 9 + 9 ? Astuce : pense à 10 + 10.", en: "What is 9 + 9? Hint: think of 10 + 10." },
    options: [
      { fr: "18", en: "18" },
      { fr: "20", en: "20" },
      { fr: "16", en: "16" },
    ],
    correctIndex: 0,
    hint: { fr: "10 + 10 = 20. Mais 9 c'est un peu moins que 10... enlève 2 au total.", en: "10 + 10 = 20. But 9 is a bit less than 10... take 2 off the total." },
    strategyId: "petits-cas",
    explanation: { fr: "10 + 10 = 20, mais chaque 9 est 1 de moins que 10, donc on enlève 1 pour chaque nombre : 20 - 2 = 18.", en: "10 + 10 = 20, but each 9 is 1 less than 10, so we remove 1 for each number: 20 - 2 = 18." },
  },
  {
    id: "ecl-cal-2",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Il y a 5 pommes dans un panier. On en ajoute 5. Puis on en enlève 2. Combien reste-t-il de pommes ?", en: "There are 5 apples in a basket. 5 more are added. Then 2 are removed. How many apples are left?" },
    options: [
      { fr: "8", en: "8" },
      { fr: "10", en: "10" },
      { fr: "7", en: "7" },
    ],
    correctIndex: 0,
    hint: { fr: "Fais les étapes l'une après l'autre : d'abord additionne, puis soustrais.", en: "Do the steps one after another: first add, then subtract." },
    strategyId: "dessiner",
    explanation: { fr: "5 + 5 = 10, puis 10 - 2 = 8. Il reste 8 pommes.", en: "5 + 5 = 10, then 10 - 2 = 8. There are 8 apples left." },
  },
  {
    id: "ecl-cal-3",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Trouve le nombre manquant : 3 + ? = 7", en: "Find the missing number: 3 + ? = 7" },
    options: [
      { fr: "4", en: "4" },
      { fr: "3", en: "3" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à l'opération inverse : 7 - 3.", en: "Think of the opposite operation: 7 - 3." },
    strategyId: "a-rebours",
    explanation: { fr: "7 - 3 = 4, donc le nombre manquant est 4. On vérifie : 3 + 4 = 7.", en: "7 - 3 = 4, so the missing number is 4. Check: 3 + 4 = 7." },
  },
  {
    id: "ecl-cal-4",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Sans compter un par un : combien y a-t-il de doigts sur 2 mains ?", en: "Without counting one by one: how many fingers are on 2 hands?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "8", en: "8" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Une main a 5 doigts. Imagine additionner 5 deux fois.", en: "One hand has 5 fingers. Imagine adding 5 twice." },
    strategyId: "chercher-motif",
    explanation: { fr: "Une main a 5 doigts, donc deux mains ont 5 + 5 = 10 doigts.", en: "One hand has 5 fingers, so two hands have 5 + 5 = 10 fingers." },
  },

  // Geometrie
  {
    id: "ecl-geo-1",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Combien de côtés a un carré ?", en: "How many sides does a square have?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "3", en: "3" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte les côtés un par un en suivant le contour de la forme.", en: "Count the sides one by one, following the outline of the shape." },
    strategyId: "dessiner",
    explanation: { fr: "Un carré a 4 côtés tous égaux.", en: "A square has 4 sides, all equal." },
  },
  {
    id: "ecl-geo-2",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Quelle forme n'a pas de coins (de sommets) ?", en: "Which shape has no corners at all?" },
    options: [
      { fr: "Le cercle", en: "The circle" },
      { fr: "Le carré", en: "The square" },
      { fr: "Le triangle", en: "The triangle" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à une forme toute ronde, sans aucune pointe.", en: "Think of a shape that's completely round, with no points." },
    strategyId: "dessiner",
    explanation: { fr: "Le cercle est une courbe fermée sans coin : il n'a aucun sommet.", en: "The circle is a closed curve with no corner: it has no vertices at all." },
  },
  {
    id: "ecl-geo-3",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Si tu plies un carré en deux bien au milieu, les deux parties sont-elles pareilles ?", en: "If you fold a square exactly in half, are the two parts the same?" },
    options: [
      { fr: "Oui, elles sont identiques", en: "Yes, they are identical" },
      { fr: "Non, elles sont différentes", en: "No, they are different" },
      { fr: "Ça dépend du jour", en: "It depends on the day" },
    ],
    correctIndex: 0,
    hint: { fr: "C'est ce qu'on appelle la symétrie : les deux moitiés se ressemblent comme un miroir.", en: "This is called symmetry: the two halves look alike, like a mirror." },
    strategyId: "dessiner",
    explanation: { fr: "Un carré plié en son milieu donne deux parties identiques : c'est un axe de symétrie.", en: "A square folded through its middle gives two identical parts: that's a line of symmetry." },
  },
  {
    id: "ecl-geo-4",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Un triangle a combien de sommets (de coins) ?", en: "How many corners (vertices) does a triangle have?" },
    options: [
      { fr: "3", en: "3" },
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte les pointes de la forme, une par une.", en: "Count the points of the shape, one by one." },
    strategyId: "dessiner",
    explanation: { fr: "Un triangle a 3 côtés et donc 3 sommets.", en: "A triangle has 3 sides and therefore 3 vertices." },
  },

  // Combinatoire
  {
    id: "ecl-com-1",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Tu as un tee-shirt rouge et un bleu, et un pantalon noir et un blanc. Combien de tenues différentes peux-tu faire ?", en: "You have a red shirt and a blue one, and black pants and white pants. How many different outfits can you make?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
      { fr: "6", en: "6" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chaque tee-shirt, il y a 2 choix de pantalon possibles.", en: "For each shirt, there are 2 possible pants choices." },
    strategyId: "essai-organise",
    explanation: { fr: "2 tee-shirts x 2 pantalons = 4 tenues : rouge-noir, rouge-blanc, bleu-noir, bleu-blanc.", en: "2 shirts x 2 pants = 4 outfits: red-black, red-white, blue-black, blue-white." },
  },
  {
    id: "ecl-com-2",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons peux-tu ranger une balle et une poupée, l'une à côté de l'autre sur une étagère ?", en: "How many ways can you arrange a ball and a doll, side by side on a shelf?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie toutes les positions possibles, une par une.", en: "Try all possible positions, one by one." },
    strategyId: "essai-organise",
    explanation: { fr: "Soit la balle est à gauche et la poupée à droite, soit l'inverse : ça fait 2 façons.", en: "Either the ball is on the left and the doll on the right, or the opposite: that's 2 ways." },
  },
  {
    id: "ecl-com-3",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 3 bonbons de couleurs différentes. Combien de façons peux-tu en choisir 1 seul à manger ?", en: "You have 3 differently colored candies. In how many ways can you choose just 1 to eat?" },
    options: [
      { fr: "3", en: "3" },
      { fr: "1", en: "1" },
      { fr: "6", en: "6" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre de bonbons disponibles.", en: "Just count the number of available candies." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 3 bonbons, donc 3 choix possibles.", en: "There are 3 candies, so 3 possible choices." },
  },
  {
    id: "ecl-com-4",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Léo a 2 chapeaux et 3 paires de lunettes. Combien de looks différents peut-il faire (un chapeau + une paire de lunettes) ?", en: "Léo has 2 hats and 3 pairs of glasses. How many different looks can he make (one hat + one pair of glasses)?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "5", en: "5" },
      { fr: "3", en: "3" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chaque chapeau, compte le nombre de lunettes possibles.", en: "For each hat, count the possible glasses." },
    strategyId: "essai-organise",
    explanation: { fr: "2 chapeaux x 3 paires de lunettes = 6 looks différents.", en: "2 hats x 3 pairs of glasses = 6 different looks." },
  },

  // ===== CHERCHEUR (8 ans) =====

  // Logique
  {
    id: "che-log-1",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Complète la suite : 2, 4, 6, 8, ... ?", en: "Complete the sequence: 2, 4, 6, 8, ... ?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "9", en: "9" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Chaque nombre augmente-t-il toujours de la même quantité ?", en: "Does each number always increase by the same amount?" },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque nombre augmente de 2 : 2, 4, 6, 8, 10.", en: "Each number increases by 2: 2, 4, 6, 8, 10." },
  },
  {
    id: "che-log-2",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Léa, Max et Nina ont chacun un animal différent : chat, chien, poisson. Léa n'a pas de chat. Max n'a pas de poisson. Nina a un chien. Qui a le chat ?", en: "Léa, Max and Nina each have a different pet: cat, dog, fish. Léa doesn't have a cat. Max doesn't have a fish. Nina has a dog. Who has the cat?" },
    options: [
      { fr: "Léa", en: "Léa" },
      { fr: "Max", en: "Max" },
      { fr: "Nina", en: "Nina" },
    ],
    correctIndex: 1,
    hint: { fr: "Élimine les possibilités une par une grâce aux indices.", en: "Eliminate the possibilities one by one using the clues." },
    strategyId: "essai-organise",
    explanation: { fr: "Nina a le chien. Léa n'a pas le chat, donc Léa a le poisson. Il reste le chat pour Max.", en: "Nina has the dog. Léa doesn't have the cat, so Léa has the fish. That leaves the cat for Max." },
  },
  {
    id: "che-log-3",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Complète : 1, 1, 2, 3, 5, ... ? (indice : additionne les deux nombres précédents)", en: "Complete: 1, 1, 2, 3, 5, ... ? (hint: add the two previous numbers)" },
    options: [
      { fr: "8", en: "8" },
      { fr: "7", en: "7" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne les deux derniers nombres de la suite : 3 + 5.", en: "Add the last two numbers of the sequence: 3 + 5." },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque nombre est la somme des deux précédents : 3 + 5 = 8.", en: "Each number is the sum of the two before it: 3 + 5 = 8." },
  },
  {
    id: "che-log-4",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Dans une course, Emma arrive avant Karim. Karim arrive avant Lina. Qui arrive en dernier ?", en: "In a race, Emma finishes before Karim. Karim finishes before Lina. Who finishes last?" },
    options: [
      { fr: "Lina", en: "Lina" },
      { fr: "Emma", en: "Emma" },
      { fr: "Karim", en: "Karim" },
    ],
    correctIndex: 0,
    hint: { fr: "Range les trois coureurs dans l'ordre d'arrivée, du premier au dernier.", en: "Sort the three runners in finishing order, first to last." },
    strategyId: "dessiner",
    explanation: { fr: "Emma avant Karim, Karim avant Lina : l'ordre est Emma, Karim, Lina. Lina arrive donc en dernier.", en: "Emma before Karim, Karim before Lina: the order is Emma, Karim, Lina. So Lina finishes last." },
  },

  // Calcul
  {
    id: "che-cal-1",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Calcule astucieusement : 25 + 19. Astuce : 19 c'est presque 20.", en: "Calculate cleverly: 25 + 19. Hint: 19 is almost 20." },
    options: [
      { fr: "44", en: "44" },
      { fr: "45", en: "45" },
      { fr: "43", en: "43" },
    ],
    correctIndex: 0,
    hint: { fr: "Remplace 19 par 20, additionne, puis enlève 1 au résultat.", en: "Replace 19 with 20, add, then subtract 1 from the result." },
    strategyId: "petits-cas",
    explanation: { fr: "25 + 20 = 45. Comme on a ajouté 1 de trop (20 au lieu de 19), on enlève 1 : 45 - 1 = 44.", en: "25 + 20 = 45. Since we added 1 too many (20 instead of 19), we subtract 1: 45 - 1 = 44." },
  },
  {
    id: "che-cal-2",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Un cahier coûte 3 euros. Combien coûtent 4 cahiers ?", en: "A notebook costs 3 euros. How much do 4 notebooks cost?" },
    options: [
      { fr: "12", en: "12" },
      { fr: "9", en: "9" },
      { fr: "16", en: "16" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne 3 quatre fois, ou multiplie 3 par 4.", en: "Add 3 four times, or multiply 3 by 4." },
    strategyId: "chercher-motif",
    explanation: { fr: "3 x 4 = 12 euros.", en: "3 x 4 = 12 euros." },
  },
  {
    id: "che-cal-3",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Trouve le nombre manquant : ? x 5 = 35", en: "Find the missing number: ? x 5 = 35" },
    options: [
      { fr: "7", en: "7" },
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à la table de multiplication de 5.", en: "Think of the 5 times table." },
    strategyId: "a-rebours",
    explanation: { fr: "5 x 7 = 35, donc le nombre manquant est 7.", en: "5 x 7 = 35, so the missing number is 7." },
  },
  {
    id: "che-cal-4",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Sarah avait des billes. Elle en a gagné 12, puis elle en a perdu 5. Elle en a maintenant 20. Combien en avait-elle au départ ?", en: "Sarah had marbles. She won 12, then lost 5. She now has 20. How many did she have at the start?" },
    options: [
      { fr: "13", en: "13" },
      { fr: "17", en: "17" },
      { fr: "7", en: "7" },
    ],
    correctIndex: 0,
    hint: { fr: "Pars du résultat final (20) et fais les opérations inverses, dans l'ordre inverse.", en: "Start from the final result (20) and do the opposite operations, in reverse order." },
    strategyId: "a-rebours",
    explanation: { fr: "En partant de 20 : on annule la perte de 5 (20 + 5 = 25), puis on annule le gain de 12 (25 - 12 = 13).", en: "Starting from 20: undo the loss of 5 (20 + 5 = 25), then undo the gain of 12 (25 - 12 = 13)." },
  },

  // Geometrie
  {
    id: "che-geo-1",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Un rectangle mesure 5 cm de long et 3 cm de large. Quel est son périmètre ?", en: "A rectangle is 5 cm long and 3 cm wide. What is its perimeter?" },
    options: [
      { fr: "16 cm", en: "16 cm" },
      { fr: "15 cm", en: "15 cm" },
      { fr: "8 cm", en: "8 cm" },
    ],
    correctIndex: 0,
    hint: { fr: "Le périmètre, c'est le tour de la forme : additionne tous les côtés.", en: "The perimeter is the distance around the shape: add up all the sides." },
    strategyId: "dessiner",
    explanation: { fr: "Un rectangle a 2 longueurs et 2 largeurs : 5 + 5 + 3 + 3 = 16 cm.", en: "A rectangle has 2 lengths and 2 widths: 5 + 5 + 3 + 3 = 16 cm." },
  },
  {
    id: "che-geo-2",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Combien de côtés a un hexagone ?", en: "How many sides does a hexagon have?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "5", en: "5" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Le préfixe 'hexa' veut dire six.", en: "The prefix 'hexa' means six." },
    strategyId: "dessiner",
    explanation: { fr: "Un hexagone a 6 côtés.", en: "A hexagon has 6 sides." },
  },
  {
    id: "che-geo-3",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Une figure a un axe de symétrie vertical. Si tu la plies en deux le long de cet axe, que se passe-t-il ?", en: "A figure has a vertical line of symmetry. If you fold it in half along that line, what happens?" },
    options: [
      { fr: "Les deux moitiés se superposent exactement", en: "The two halves overlap exactly" },
      { fr: "Les deux moitiés sont différentes", en: "The two halves are different" },
      { fr: "Rien de particulier", en: "Nothing in particular" },
    ],
    correctIndex: 0,
    hint: { fr: "La symétrie veut dire que les deux parties sont comme un miroir l'une de l'autre.", en: "Symmetry means the two parts are like a mirror of each other." },
    strategyId: "dessiner",
    explanation: { fr: "Par définition, un axe de symétrie sépare une figure en deux parties qui se superposent parfaitement.", en: "By definition, a line of symmetry splits a figure into two parts that overlap perfectly." },
  },
  {
    id: "che-geo-4",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Un carré a un côté de 4 cm. Quelle est son aire ?", en: "A square has a side of 4 cm. What is its area?" },
    options: [
      { fr: "16 cm²", en: "16 cm²" },
      { fr: "8 cm²", en: "8 cm²" },
      { fr: "12 cm²", en: "12 cm²" },
    ],
    correctIndex: 0,
    hint: { fr: "L'aire d'un carré, c'est le côté multiplié par lui-même.", en: "The area of a square is the side multiplied by itself." },
    strategyId: "petits-cas",
    explanation: { fr: "4 x 4 = 16 cm².", en: "4 x 4 = 16 cm²." },
  },

  // Combinatoire
  {
    id: "che-com-1",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 3 t-shirts et 2 shorts. Combien de tenues différentes peux-tu former ?", en: "You have 3 t-shirts and 2 shorts. How many different outfits can you form?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "5", en: "5" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chaque t-shirt, compte le nombre de shorts possibles, puis additionne.", en: "For each t-shirt, count the possible shorts, then add them up." },
    strategyId: "essai-organise",
    explanation: { fr: "3 t-shirts x 2 shorts = 6 tenues différentes.", en: "3 t-shirts x 2 shorts = 6 different outfits." },
  },
  {
    id: "che-com-2",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Combien de nombres à 2 chiffres peux-tu former avec les chiffres 1, 2 et 3, sans répéter de chiffre ?", en: "How many 2-digit numbers can you form with the digits 1, 2 and 3, without repeating a digit?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "9", en: "9" },
      { fr: "3", en: "3" },
    ],
    correctIndex: 0,
    hint: { fr: "Écris toutes les possibilités dans un ordre organisé pour ne pas te tromper.", en: "Write out all the possibilities in an organized order so you don't make mistakes." },
    strategyId: "compter-organise",
    explanation: { fr: "Les possibilités sont : 12, 13, 21, 23, 31, 32. Cela fait 6 nombres.", en: "The possibilities are: 12, 13, 21, 23, 31, 32. That's 6 numbers." },
  },
  {
    id: "che-com-3",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Dans une classe, il y a 4 équipes possibles pour un jeu. Chaque enfant doit choisir une équipe. Combien de choix possibles as-tu ?", en: "In a class, there are 4 possible teams for a game. Each child must choose a team. How many possible choices do you have?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre d'équipes disponibles.", en: "Just count the number of available teams." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 4 équipes, donc 4 choix possibles.", en: "There are 4 teams, so 4 possible choices." },
  },
  {
    id: "che-com-4",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons différentes peux-tu ranger 3 livres A, B, C côte à côte sur une étagère ?", en: "How many different ways can you arrange 3 books A, B, C side by side on a shelf?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "3", en: "3" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie toutes les combinaisons en commençant par chaque livre à tour de rôle.", en: "Try all combinations by starting with each book in turn." },
    strategyId: "essai-organise",
    explanation: { fr: "Il y a 3 choix pour le premier livre, puis 2 pour le second, puis 1 pour le dernier : 3 x 2 x 1 = 6.", en: "There are 3 choices for the first book, then 2 for the second, then 1 for the last: 3 x 2 x 1 = 6." },
  },

  // ===== CHAMPION (11 ans) =====

  // Logique
  {
    id: "cha-log-1",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Quatre amis (Ana, Ben, Cléo, Dan) sont classés à une course. Ana n'est pas 1ère ni dernière. Ben arrive juste après Ana. Dan est 1er. Cléo est dernière. Quel est le classement complet ?", en: "Four friends (Ana, Ben, Cléo, Dan) are ranked in a race. Ana is neither 1st nor last. Ben finishes right after Ana. Dan is 1st. Cléo is last. What is the full ranking?" },
    options: [
      { fr: "Dan, Ana, Ben, Cléo", en: "Dan, Ana, Ben, Cléo" },
      { fr: "Dan, Ben, Ana, Cléo", en: "Dan, Ben, Ana, Cléo" },
      { fr: "Ana, Dan, Ben, Cléo", en: "Ana, Dan, Ben, Cléo" },
    ],
    correctIndex: 0,
    hint: { fr: "Place d'abord ceux dont la position est certaine (Dan et Cléo), puis déduis le reste.", en: "Place first the ones whose position is certain (Dan and Cléo), then deduce the rest." },
    strategyId: "essai-organise",
    explanation: { fr: "Dan est 1er et Cléo est 4ème. Ana n'est ni 1ère ni dernière, donc elle est 2ème ou 3ème. Ben arrive juste après Ana : si Ana était 3ème, Ben serait 4ème, ce qui est la place de Cléo. Donc Ana est 2ème et Ben 3ème.", en: "Dan is 1st and Cléo is 4th. Ana is neither 1st nor last, so she is 2nd or 3rd. Ben finishes right after Ana: if Ana were 3rd, Ben would be 4th, which is Cléo's spot. So Ana is 2nd and Ben is 3rd." },
  },
  {
    id: "cha-log-2",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Suite logique : 1, 4, 9, 16, 25, ... ? (indice : ce sont des carrés parfaits)", en: "Logical sequence: 1, 4, 9, 16, 25, ... ? (hint: these are perfect squares)" },
    options: [
      { fr: "36", en: "36" },
      { fr: "30", en: "30" },
      { fr: "35", en: "35" },
    ],
    correctIndex: 0,
    hint: { fr: "Ce sont les carrés de 1, 2, 3, 4, 5... Quel est le carré de 6 ?", en: "These are the squares of 1, 2, 3, 4, 5... What is the square of 6?" },
    strategyId: "chercher-motif",
    explanation: { fr: "Les termes sont 1², 2², 3², 4², 5², donc le suivant est 6² = 36.", en: "The terms are 1², 2², 3², 4², 5², so the next one is 6² = 36." },
  },
  {
    id: "cha-log-3",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Un menteur ment toujours, un honnête dit toujours la vérité. Un enfant affirme : 'Je suis un menteur.' Est-ce possible ?", en: "A liar always lies, an honest person always tells the truth. A child says: 'I am a liar.' Is this possible?" },
    options: [
      { fr: "Non, c'est impossible (contradiction)", en: "No, it's impossible (a contradiction)" },
      { fr: "Oui, c'est forcément un menteur", en: "Yes, it must be a liar" },
      { fr: "Oui, c'est forcément un honnête", en: "Yes, it must be honest" },
    ],
    correctIndex: 0,
    hint: { fr: "Teste les deux hypothèses (menteur, honnête) une par une et regarde si elles tiennent debout.", en: "Test both hypotheses (liar, honest) one by one and see if they hold up." },
    strategyId: "essai-organise",
    explanation: { fr: "Si c'était un honnête, il dirait la vérité, donc il serait un menteur : contradiction. Si c'était un menteur, sa phrase serait un mensonge, donc il serait honnête : contradiction aussi. La phrase est donc impossible.", en: "If honest, they'd be telling the truth, so they'd be a liar: contradiction. If a liar, the statement would be a lie, so they'd be honest: also a contradiction. So the statement is impossible." },
  },
  {
    id: "cha-log-4",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Dans une suite, chaque terme est le double du précédent moins 1 : 2, 3, 5, 9, ... ?", en: "In a sequence, each term is double the previous one minus 1: 2, 3, 5, 9, ... ?" },
    options: [
      { fr: "17", en: "17" },
      { fr: "16", en: "16" },
      { fr: "18", en: "18" },
    ],
    correctIndex: 0,
    hint: { fr: "Applique la règle 'double moins 1' au dernier nombre de la suite (9).", en: "Apply the 'double minus 1' rule to the last number in the sequence (9)." },
    strategyId: "chercher-motif",
    explanation: { fr: "9 x 2 - 1 = 17.", en: "9 x 2 - 1 = 17." },
  },

  // Calcul
  {
    id: "cha-cal-1",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Calcule astucieusement : 99 x 4. Astuce : 99 c'est presque 100.", en: "Calculate cleverly: 99 x 4. Hint: 99 is almost 100." },
    options: [
      { fr: "396", en: "396" },
      { fr: "392", en: "392" },
      { fr: "400", en: "400" },
    ],
    correctIndex: 0,
    hint: { fr: "Remplace 99 par 100, multiplie, puis enlève 4 (un 4 par 99 remplacé).", en: "Replace 99 with 100, multiply, then subtract 4 (one 4 for the 99 replaced)." },
    strategyId: "petits-cas",
    explanation: { fr: "100 x 4 = 400. Comme on a ajouté 1 de trop à chacun des 4 groupes, on enlève 4 : 400 - 4 = 396.", en: "100 x 4 = 400. Since we added 1 too many in each of the 4 groups, we subtract 4: 400 - 4 = 396." },
  },
  {
    id: "cha-cal-2",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "La somme de trois nombres entiers consécutifs est 45. Quel est le nombre du milieu ?", en: "The sum of three consecutive whole numbers is 45. What is the middle number?" },
    options: [
      { fr: "15", en: "15" },
      { fr: "14", en: "14" },
      { fr: "16", en: "16" },
    ],
    correctIndex: 0,
    hint: { fr: "La somme de trois nombres consécutifs vaut toujours 3 fois le nombre du milieu.", en: "The sum of three consecutive numbers is always 3 times the middle number." },
    strategyId: "a-rebours",
    explanation: { fr: "45 / 3 = 15. On vérifie : 14 + 15 + 16 = 45.", en: "45 / 3 = 15. Check: 14 + 15 + 16 = 45." },
  },
  {
    id: "cha-cal-3",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Un nombre multiplié par lui-même donne 144. Quel est ce nombre ?", en: "A number multiplied by itself gives 144. What is that number?" },
    options: [
      { fr: "12", en: "12" },
      { fr: "11", en: "11" },
      { fr: "13", en: "13" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie quelques nombres proches de 10 et calcule leur carré.", en: "Try a few numbers close to 10 and calculate their square." },
    strategyId: "essai-organise",
    explanation: { fr: "12 x 12 = 144.", en: "12 x 12 = 144." },
  },
  {
    id: "cha-cal-4",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Combien y a-t-il de multiples de 7 entre 1 et 50 ?", en: "How many multiples of 7 are there between 1 and 50?" },
    options: [
      { fr: "7", en: "7" },
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Liste les multiples de 7 un par un jusqu'à dépasser 50.", en: "List the multiples of 7 one by one until you go past 50." },
    strategyId: "compter-organise",
    explanation: { fr: "7, 14, 21, 28, 35, 42, 49 : cela fait 7 multiples de 7 entre 1 et 50.", en: "7, 14, 21, 28, 35, 42, 49: that's 7 multiples of 7 between 1 and 50." },
  },

  // Geometrie
  {
    id: "cha-geo-1",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un rectangle a une aire de 24 cm² et une largeur de 4 cm. Quelle est sa longueur ?", en: "A rectangle has an area of 24 cm² and a width of 4 cm. What is its length?" },
    options: [
      { fr: "6 cm", en: "6 cm" },
      { fr: "8 cm", en: "8 cm" },
      { fr: "4 cm", en: "4 cm" },
    ],
    correctIndex: 0,
    hint: { fr: "L'aire c'est longueur fois largeur : utilise l'opération inverse (division).", en: "Area is length times width: use the opposite operation (division)." },
    strategyId: "a-rebours",
    explanation: { fr: "24 / 4 = 6 cm.", en: "24 / 4 = 6 cm." },
  },
  {
    id: "cha-geo-2",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "La somme des angles d'un triangle fait toujours 180°. Un triangle a deux angles de 70° et 60°. Quel est le troisième angle ?", en: "The angles of a triangle always add up to 180°. A triangle has two angles of 70° and 60°. What is the third angle?" },
    options: [
      { fr: "50°", en: "50°" },
      { fr: "60°", en: "60°" },
      { fr: "40°", en: "40°" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne les deux angles connus, puis soustrais le total à 180°.", en: "Add the two known angles, then subtract the total from 180°." },
    strategyId: "a-rebours",
    explanation: { fr: "70 + 60 = 130°. 180 - 130 = 50°.", en: "70 + 60 = 130°. 180 - 130 = 50°." },
  },
  {
    id: "cha-geo-3",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un carré a un périmètre de 20 cm. Quelle est son aire ?", en: "A square has a perimeter of 20 cm. What is its area?" },
    options: [
      { fr: "25 cm²", en: "25 cm²" },
      { fr: "20 cm²", en: "20 cm²" },
      { fr: "16 cm²", en: "16 cm²" },
    ],
    correctIndex: 0,
    hint: { fr: "Trouve d'abord la longueur d'un côté (périmètre divisé par 4), puis calcule l'aire.", en: "First find the length of one side (perimeter divided by 4), then calculate the area." },
    strategyId: "a-rebours",
    explanation: { fr: "20 / 4 = 5 cm de côté. L'aire est 5 x 5 = 25 cm².", en: "20 / 4 = 5 cm per side. The area is 5 x 5 = 25 cm²." },
  },
  {
    id: "cha-geo-4",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Combien de diagonales possède un pentagone (5 côtés) ?", en: "How many diagonals does a pentagon (5 sides) have?" },
    options: [
      { fr: "5", en: "5" },
      { fr: "4", en: "4" },
      { fr: "10", en: "10" },
    ],
    correctIndex: 0,
    hint: { fr: "Depuis chaque sommet, compte les diagonales possibles, puis fais attention à ne pas les compter deux fois.", en: "From each vertex, count the possible diagonals, then be careful not to count them twice." },
    strategyId: "compter-organise",
    explanation: { fr: "Depuis chaque sommet partent 2 diagonales (5 sommets x 2 = 10), mais chaque diagonale est comptée deux fois : 10 / 2 = 5.", en: "From each vertex, 2 diagonals start (5 vertices x 2 = 10), but each diagonal is counted twice: 10 / 2 = 5." },
  },

  // Combinatoire
  {
    id: "cha-com-1",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons différentes peux-tu ranger 4 livres différents sur une étagère ?", en: "How many different ways can you arrange 4 different books on a shelf?" },
    options: [
      { fr: "24", en: "24" },
      { fr: "16", en: "16" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour le premier livre il y a 4 choix, puis 3, puis 2, puis 1 : multiplie ces nombres.", en: "For the first book there are 4 choices, then 3, then 2, then 1: multiply these numbers." },
    strategyId: "essai-organise",
    explanation: { fr: "4 x 3 x 2 x 1 = 24.", en: "4 x 3 x 2 x 1 = 24." },
  },
  {
    id: "cha-com-2",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Dans un groupe de 5 amis, combien de poignées de main différentes peuvent être échangées si chacun serre la main de chaque autre une seule fois ?", en: "In a group of 5 friends, how many different handshakes can happen if everyone shakes each other's hand exactly once?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "20", en: "20" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Chaque ami serre la main de 4 autres, mais chaque poignée est comptée deux fois : divise par 2.", en: "Each friend shakes 4 other hands, but each handshake gets counted twice: divide by 2." },
    strategyId: "compter-organise",
    explanation: { fr: "5 amis x 4 poignées chacun = 20, mais chaque poignée est comptée deux fois : 20 / 2 = 10.", en: "5 friends x 4 handshakes each = 20, but each handshake is counted twice: 20 / 2 = 10." },
  },
  {
    id: "cha-com-3",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de nombres pairs à 3 chiffres peux-tu former avec les chiffres 1, 2, 3, 4, sans répéter de chiffre ?", en: "How many 3-digit even numbers can you form with the digits 1, 2, 3, 4, without repeating a digit?" },
    options: [
      { fr: "12", en: "12" },
      { fr: "8", en: "8" },
      { fr: "24", en: "24" },
    ],
    correctIndex: 0,
    hint: { fr: "Fixe d'abord le dernier chiffre (il doit être pair : 2 ou 4), puis compte les façons de placer les deux premiers.", en: "First fix the last digit (it must be even: 2 or 4), then count the ways to place the first two." },
    strategyId: "essai-organise",
    explanation: { fr: "Le dernier chiffre a 2 choix possibles (2 ou 4). Pour chacun, il reste 3 chiffres pour les 2 premières places, ce qui donne 3 x 2 = 6 façons. Au total : 2 x 6 = 12.", en: "The last digit has 2 possible choices (2 or 4). For each, 3 digits remain for the first 2 spots, giving 3 x 2 = 6 ways. In total: 2 x 6 = 12." },
  },
  {
    id: "cha-com-4",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons peux-tu choisir 2 fruits parmi 4 fruits différents pour faire une salade de fruits ?", en: "How many ways can you choose 2 fruits out of 4 different fruits to make a fruit salad?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Liste toutes les paires possibles de façon organisée, sans en compter deux fois.", en: "List all the possible pairs in an organized way, without counting any twice." },
    strategyId: "compter-organise",
    explanation: { fr: "Avec 4 fruits (A, B, C, D), les paires possibles sont AB, AC, AD, BC, BD, CD : cela fait 6 paires.", en: "With 4 fruits (A, B, C, D), the possible pairs are AB, AC, AD, BC, BD, CD: that's 6 pairs." },
  },

  // ===== ECLAIREUR (6 ans) - lot supplementaire =====

  // Logique
  {
    id: "ecl-log-5",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Un carré, un cercle, un triangle, un carré, un cercle, ... Quelle est la forme suivante ?", en: "A square, a circle, a triangle, a square, a circle, ... What shape comes next?" },
    options: [
      { fr: "Un triangle", en: "A triangle" },
      { fr: "Un carré", en: "A square" },
      { fr: "Un cercle", en: "A circle" },
    ],
    correctIndex: 0,
    hint: { fr: "Le motif se répète toutes les 3 formes : carré, cercle, triangle.", en: "The pattern repeats every 3 shapes: square, circle, triangle." },
    strategyId: "chercher-motif",
    explanation: { fr: "Le motif carré, cercle, triangle se répète. Après cercle vient toujours triangle.", en: "The pattern square, circle, triangle repeats. After circle always comes triangle." },
  },
  {
    id: "ecl-log-6",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Range du plus petit au plus grand : une souris, un chat, un éléphant. Qui est le plus grand ?", en: "Sort from smallest to biggest: a mouse, a cat, an elephant. Who is the biggest?" },
    options: [
      { fr: "L'éléphant", en: "The elephant" },
      { fr: "La souris", en: "The mouse" },
      { fr: "Le chat", en: "The cat" },
    ],
    correctIndex: 0,
    hint: { fr: "Imagine les trois animaux côte à côte pour comparer leur taille.", en: "Picture the three animals side by side to compare their size." },
    strategyId: "dessiner",
    explanation: { fr: "Parmi ces trois animaux, l'éléphant est de loin le plus grand.", en: "Among these three animals, the elephant is by far the biggest." },
  },
  {
    id: "ecl-log-7",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Parmi ces animaux, lequel ne sait pas voler : un oiseau, un papillon, un chat ?", en: "Which of these animals cannot fly: a bird, a butterfly, a cat?" },
    options: [
      { fr: "Le chat", en: "The cat" },
      { fr: "L'oiseau", en: "The bird" },
      { fr: "Le papillon", en: "The butterfly" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à quel animal reste toujours au sol.", en: "Think about which animal always stays on the ground." },
    strategyId: "essai-organise",
    explanation: { fr: "L'oiseau et le papillon volent grâce à leurs ailes. Le chat n'a pas d'ailes : il ne vole pas.", en: "The bird and the butterfly fly with their wings. The cat has no wings: it cannot fly." },
  },
  {
    id: "ecl-log-8",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Pour aller à l'école, il faut tourner à gauche puis à droite. Si tu tournes à droite puis à gauche, arrives-tu au bon endroit ?", en: "To get to school, you must turn left then right. If you turn right then left, do you end up in the right place?" },
    options: [
      { fr: "Non, l'ordre des étapes compte", en: "No, the order of the steps matters" },
      { fr: "Oui, ça revient toujours au même", en: "Yes, it always comes out the same" },
      { fr: "Ça ne change jamais rien", en: "It never makes any difference" },
    ],
    correctIndex: 0,
    hint: { fr: "Imagine-toi marcher dans la rue et suivre chaque étape dans l'ordre inverse.", en: "Imagine walking down the street and following each step in reverse order." },
    strategyId: "dessiner",
    explanation: { fr: "Changer l'ordre des virages te fait suivre un chemin différent : tu n'arrives pas forcément au bon endroit.", en: "Changing the order of the turns makes you follow a different path: you won't necessarily end up in the right place." },
  },

  // Calcul
  {
    id: "ecl-cal-5",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Combien font 5 + 5 + 5 ? Astuce : c'est 3 fois 5.", en: "What is 5 + 5 + 5? Hint: it's 3 times 5." },
    options: [
      { fr: "15", en: "15" },
      { fr: "10", en: "10" },
      { fr: "20", en: "20" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne 5 trois fois de suite, un pas à la fois.", en: "Add 5 three times in a row, one step at a time." },
    strategyId: "chercher-motif",
    explanation: { fr: "5 + 5 = 10, puis 10 + 5 = 15.", en: "5 + 5 = 10, then 10 + 5 = 15." },
  },
  {
    id: "ecl-cal-6",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Tu as 10 bonbons. Tu en donnes 3 à ton frère. Combien t'en reste-t-il ?", en: "You have 10 candies. You give 3 to your brother. How many do you have left?" },
    options: [
      { fr: "7", en: "7" },
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Enlève 3 à 10, un par un si besoin.", en: "Take 3 away from 10, one at a time if needed." },
    strategyId: "dessiner",
    explanation: { fr: "10 - 3 = 7.", en: "10 - 3 = 7." },
  },
  {
    id: "ecl-cal-7",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Trouve le nombre manquant : 8 - ? = 5", en: "Find the missing number: 8 - ? = 5" },
    options: [
      { fr: "3", en: "3" },
      { fr: "2", en: "2" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à l'opération inverse : 8 - 5.", en: "Think of the opposite operation: 8 - 5." },
    strategyId: "a-rebours",
    explanation: { fr: "8 - 5 = 3, donc le nombre manquant est 3.", en: "8 - 5 = 3, so the missing number is 3." },
  },
  {
    id: "ecl-cal-8",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Combien font 2 + 2 + 2 + 2 ? Astuce : c'est comme 2 fois 4.", en: "What is 2 + 2 + 2 + 2? Hint: it's like 2 times 4." },
    options: [
      { fr: "8", en: "8" },
      { fr: "6", en: "6" },
      { fr: "10", en: "10" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne 2 quatre fois de suite.", en: "Add 2 four times in a row." },
    strategyId: "chercher-motif",
    explanation: { fr: "2 + 2 + 2 + 2 = 8.", en: "2 + 2 + 2 + 2 = 8." },
  },

  // Geometrie
  {
    id: "ecl-geo-5",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Combien de côtés a un rectangle ?", en: "How many sides does a rectangle have?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "3", en: "3" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte les côtés un par un en suivant le contour.", en: "Count the sides one by one, following the outline." },
    strategyId: "dessiner",
    explanation: { fr: "Un rectangle a 4 côtés : 2 longs et 2 courts.", en: "A rectangle has 4 sides: 2 long and 2 short." },
  },
  {
    id: "ecl-geo-6",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Quelle forme ressemble le plus à une porte ?", en: "Which shape looks most like a door?" },
    options: [
      { fr: "Le rectangle", en: "The rectangle" },
      { fr: "Le cercle", en: "The circle" },
      { fr: "Le triangle", en: "The triangle" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à la forme d'une porte que tu ouvres chez toi.", en: "Think of the shape of a door you open at home." },
    strategyId: "dessiner",
    explanation: { fr: "Une porte est haute et droite, comme un rectangle.", en: "A door is tall and straight, like a rectangle." },
  },
  {
    id: "ecl-geo-7",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Un cercle a-t-il des côtés droits ?", en: "Does a circle have straight sides?" },
    options: [
      { fr: "Non, il est tout rond", en: "No, it's all round" },
      { fr: "Oui, il en a quatre", en: "Yes, it has four" },
      { fr: "Oui, il en a trois", en: "Yes, it has three" },
    ],
    correctIndex: 0,
    hint: { fr: "Trace un cercle avec ton doigt dans les airs : sens-tu des angles ?", en: "Trace a circle with your finger in the air: do you feel any corners?" },
    strategyId: "dessiner",
    explanation: { fr: "Un cercle est une courbe continue, sans aucun côté droit.", en: "A circle is a continuous curve, with no straight side at all." },
  },
  {
    id: "ecl-geo-8",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Combien de sommets (coins) a un cercle ?", en: "How many corners does a circle have?" },
    options: [
      { fr: "0", en: "0" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Un sommet, c'est une pointe. Un cercle a-t-il des pointes ?", en: "A corner is a point. Does a circle have any points?" },
    strategyId: "dessiner",
    explanation: { fr: "Le cercle n'a aucune pointe : il a donc 0 sommet.", en: "The circle has no points at all: so it has 0 corners." },
  },

  // Combinatoire
  {
    id: "ecl-com-5",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 2 chapeaux, un rouge et un bleu. Combien de façons peux-tu en porter un seul ?", en: "You have 2 hats, one red and one blue. In how many ways can you wear just one?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre de chapeaux disponibles.", en: "Just count the number of available hats." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 2 chapeaux, donc 2 choix possibles.", en: "There are 2 hats, so 2 possible choices." },
  },
  {
    id: "ecl-com-6",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons peux-tu empiler un cube rouge et un cube bleu, l'un sur l'autre ?", en: "In how many ways can you stack a red cube and a blue cube, one on top of the other?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie les deux possibilités : lequel est en haut ?", en: "Try both possibilities: which one is on top?" },
    strategyId: "essai-organise",
    explanation: { fr: "Soit le rouge est en haut, soit le bleu est en haut : ça fait 2 façons.", en: "Either red is on top, or blue is on top: that's 2 ways." },
  },
  {
    id: "ecl-com-7",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 4 fruits différents. Combien de façons peux-tu en choisir 1 seul à manger ?", en: "You have 4 different fruits. In how many ways can you choose just 1 to eat?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre de fruits disponibles.", en: "Just count the number of available fruits." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 4 fruits, donc 4 choix possibles.", en: "There are 4 fruits, so 4 possible choices." },
  },
  {
    id: "ecl-com-8",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Léa a 2 rubans de couleurs différentes. Combien de coiffures différentes peut-elle faire avec un seul ruban à la fois ?", en: "Léa has 2 differently colored ribbons. How many different hairstyles can she make with just one ribbon at a time?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre de rubans.", en: "Just count the number of ribbons." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 2 rubans, donc 2 coiffures possibles.", en: "There are 2 ribbons, so 2 possible hairstyles." },
  },

  // ===== CHERCHEUR (8 ans) - lot supplementaire =====

  // Logique
  {
    id: "che-log-5",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Complète la suite : 5, 10, 15, 20, ... ?", en: "Complete the sequence: 5, 10, 15, 20, ... ?" },
    options: [
      { fr: "25", en: "25" },
      { fr: "24", en: "24" },
      { fr: "30", en: "30" },
    ],
    correctIndex: 0,
    hint: { fr: "Chaque nombre augmente-t-il toujours de la même quantité ?", en: "Does each number always increase by the same amount?" },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque nombre augmente de 5 : 5, 10, 15, 20, 25.", en: "Each number increases by 5: 5, 10, 15, 20, 25." },
  },
  {
    id: "che-log-6",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Trois enfants ont chacun un fruit différent : pomme, banane, orange. Zoé n'a pas de pomme. Tom a une orange. Qui a la pomme ?", en: "Three kids each have a different fruit: apple, banana, orange. Zoé doesn't have an apple. Tom has an orange. Who has the apple?" },
    options: [
      { fr: "Léo", en: "Léo" },
      { fr: "Zoé", en: "Zoé" },
      { fr: "Tom", en: "Tom" },
    ],
    correctIndex: 0,
    hint: { fr: "Élimine les possibilités une par une grâce aux indices.", en: "Eliminate the possibilities one by one using the clues." },
    strategyId: "essai-organise",
    explanation: { fr: "Tom a l'orange. Zoé n'a pas la pomme, donc elle a la banane. Il reste la pomme pour Léo.", en: "Tom has the orange. Zoé doesn't have the apple, so she has the banana. That leaves the apple for Léo." },
  },
  {
    id: "che-log-7",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Complète : 2, 6, 18, 54, ... ? (indice : multiplie par 3)", en: "Complete: 2, 6, 18, 54, ... ? (hint: multiply by 3)" },
    options: [
      { fr: "162", en: "162" },
      { fr: "108", en: "108" },
      { fr: "216", en: "216" },
    ],
    correctIndex: 0,
    hint: { fr: "Multiplie le dernier nombre de la suite (54) par 3.", en: "Multiply the last number in the sequence (54) by 3." },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque nombre est multiplié par 3 : 54 x 3 = 162.", en: "Each number is multiplied by 3: 54 x 3 = 162." },
  },
  {
    id: "che-log-8",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Dans une file, Nina est devant Sam. Sam est devant Elio. Qui est le premier de la file ?", en: "In a line, Nina is ahead of Sam. Sam is ahead of Elio. Who is first in line?" },
    options: [
      { fr: "Nina", en: "Nina" },
      { fr: "Sam", en: "Sam" },
      { fr: "Elio", en: "Elio" },
    ],
    correctIndex: 0,
    hint: { fr: "Range les trois enfants dans l'ordre de la file, du premier au dernier.", en: "Sort the three kids in line order, first to last." },
    strategyId: "dessiner",
    explanation: { fr: "Nina avant Sam, Sam avant Elio : l'ordre est Nina, Sam, Elio. Nina est donc première.", en: "Nina before Sam, Sam before Elio: the order is Nina, Sam, Elio. So Nina is first." },
  },

  // Calcul
  {
    id: "che-cal-5",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Calcule astucieusement : 48 + 29. Astuce : 29 c'est presque 30.", en: "Calculate cleverly: 48 + 29. Hint: 29 is almost 30." },
    options: [
      { fr: "77", en: "77" },
      { fr: "78", en: "78" },
      { fr: "76", en: "76" },
    ],
    correctIndex: 0,
    hint: { fr: "Remplace 29 par 30, additionne, puis enlève 1 au résultat.", en: "Replace 29 with 30, add, then subtract 1 from the result." },
    strategyId: "petits-cas",
    explanation: { fr: "48 + 30 = 78. Comme on a ajouté 1 de trop, on enlève 1 : 78 - 1 = 77.", en: "48 + 30 = 78. Since we added 1 too many, we subtract 1: 78 - 1 = 77." },
  },
  {
    id: "che-cal-6",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Un paquet de bonbons coûte 4 euros. Combien coûtent 6 paquets ?", en: "A pack of candy costs 4 euros. How much do 6 packs cost?" },
    options: [
      { fr: "24", en: "24" },
      { fr: "20", en: "20" },
      { fr: "28", en: "28" },
    ],
    correctIndex: 0,
    hint: { fr: "Multiplie 4 par 6.", en: "Multiply 4 by 6." },
    strategyId: "chercher-motif",
    explanation: { fr: "4 x 6 = 24 euros.", en: "4 x 6 = 24 euros." },
  },
  {
    id: "che-cal-7",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Trouve le nombre manquant : ? x 4 = 28", en: "Find the missing number: ? x 4 = 28" },
    options: [
      { fr: "7", en: "7" },
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à la table de multiplication de 4.", en: "Think of the 4 times table." },
    strategyId: "a-rebours",
    explanation: { fr: "4 x 7 = 28, donc le nombre manquant est 7.", en: "4 x 7 = 28, so the missing number is 7." },
  },
  {
    id: "che-cal-8",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Léo avait de l'argent. Il a dépensé 8 euros, puis reçu 15 euros. Il a maintenant 22 euros. Combien avait-il au départ ?", en: "Léo had some money. He spent 8 euros, then received 15 euros. He now has 22 euros. How much did he have at the start?" },
    options: [
      { fr: "15", en: "15" },
      { fr: "29", en: "29" },
      { fr: "7", en: "7" },
    ],
    correctIndex: 0,
    hint: { fr: "Pars de 22 et fais les opérations inverses, dans l'ordre inverse.", en: "Start from 22 and do the opposite operations, in reverse order." },
    strategyId: "a-rebours",
    explanation: { fr: "En partant de 22 : on annule le +15 (22 - 15 = 7), puis on annule le -8 (7 + 8 = 15).", en: "Starting from 22: undo the +15 (22 - 15 = 7), then undo the -8 (7 + 8 = 15)." },
  },

  // Geometrie
  {
    id: "che-geo-5",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Un rectangle mesure 6 cm de long et 2 cm de large. Quelle est son aire ?", en: "A rectangle is 6 cm long and 2 cm wide. What is its area?" },
    options: [
      { fr: "12 cm²", en: "12 cm²" },
      { fr: "8 cm²", en: "8 cm²" },
      { fr: "16 cm²", en: "16 cm²" },
    ],
    correctIndex: 0,
    hint: { fr: "L'aire d'un rectangle, c'est longueur fois largeur.", en: "The area of a rectangle is length times width." },
    strategyId: "petits-cas",
    explanation: { fr: "6 x 2 = 12 cm².", en: "6 x 2 = 12 cm²." },
  },
  {
    id: "che-geo-6",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Combien de côtés a un octogone ?", en: "How many sides does an octagon have?" },
    options: [
      { fr: "8", en: "8" },
      { fr: "6", en: "6" },
      { fr: "10", en: "10" },
    ],
    correctIndex: 0,
    hint: { fr: "Le préfixe 'octo' veut dire huit.", en: "The prefix 'octo' means eight." },
    strategyId: "dessiner",
    explanation: { fr: "Un octogone a 8 côtés.", en: "An octagon has 8 sides." },
  },
  {
    id: "che-geo-7",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Une figure a 2 axes de symétrie. Si tu la plies selon chaque axe, que se passe-t-il ?", en: "A figure has 2 lines of symmetry. If you fold it along each line, what happens?" },
    options: [
      { fr: "Les deux moitiés se superposent, à chaque fois", en: "The two halves overlap, every time" },
      { fr: "Seul un des deux pliages fonctionne", en: "Only one of the two folds works" },
      { fr: "Aucun des deux pliages ne fonctionne", en: "Neither fold works" },
    ],
    correctIndex: 0,
    hint: { fr: "Un axe de symétrie fonctionne toujours, quel que soit le nombre d'axes.", en: "A line of symmetry always works, no matter how many there are." },
    strategyId: "dessiner",
    explanation: { fr: "Par définition, chaque axe de symétrie sépare la figure en deux parties identiques.", en: "By definition, each line of symmetry splits the figure into two identical parts." },
  },
  {
    id: "che-geo-8",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Un carré a un périmètre de 12 cm. Quelle est la longueur d'un côté ?", en: "A square has a perimeter of 12 cm. What is the length of one side?" },
    options: [
      { fr: "3 cm", en: "3 cm" },
      { fr: "4 cm", en: "4 cm" },
      { fr: "6 cm", en: "6 cm" },
    ],
    correctIndex: 0,
    hint: { fr: "Un carré a 4 côtés égaux : divise le périmètre par 4.", en: "A square has 4 equal sides: divide the perimeter by 4." },
    strategyId: "a-rebours",
    explanation: { fr: "12 / 4 = 3 cm.", en: "12 / 4 = 3 cm." },
  },

  // Combinatoire
  {
    id: "che-com-5",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons différentes peux-tu ranger une voiture et un ballon côte à côte ?", en: "How many different ways can you arrange a car and a ball side by side?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie les deux ordres possibles.", en: "Try both possible orders." },
    strategyId: "essai-organise",
    explanation: { fr: "Soit la voiture est à gauche, soit le ballon est à gauche : ça fait 2 façons.", en: "Either the car is on the left, or the ball is on the left: that's 2 ways." },
  },
  {
    id: "che-com-6",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 4 couleurs de crayons. Combien de choix as-tu pour colorier un dessin avec une seule couleur ?", en: "You have 4 pencil colors. How many choices do you have to color a drawing with a single color?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre de couleurs disponibles.", en: "Just count the number of available colors." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 4 couleurs, donc 4 choix possibles.", en: "There are 4 colors, so 4 possible choices." },
  },
  {
    id: "che-com-7",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Combien de nombres à 2 chiffres peux-tu former avec 4 et 5, sans répéter de chiffre ?", en: "How many 2-digit numbers can you form with 4 and 5, without repeating a digit?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "4", en: "4" },
      { fr: "1", en: "1" },
    ],
    correctIndex: 0,
    hint: { fr: "Liste les deux possibilités : 45 et 54.", en: "List the two possibilities: 45 and 54." },
    strategyId: "compter-organise",
    explanation: { fr: "On peut former 45 et 54 : cela fait 2 nombres.", en: "You can form 45 and 54: that's 2 numbers." },
  },
  {
    id: "che-com-8",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Dans une équipe de 3 amis, combien de façons peux-tu choisir un capitaine ?", en: "In a team of 3 friends, how many ways can you choose a captain?" },
    options: [
      { fr: "3", en: "3" },
      { fr: "2", en: "2" },
      { fr: "6", en: "6" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre d'amis dans l'équipe.", en: "Just count the number of friends in the team." },
    strategyId: "compter-organise",
    explanation: { fr: "Chacun des 3 amis peut devenir capitaine : cela fait 3 choix possibles.", en: "Each of the 3 friends could become captain: that's 3 possible choices." },
  },

  // ===== CHAMPION (11 ans) - lot supplementaire =====

  // Logique
  {
    id: "cha-log-5",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Suite : 3, 6, 12, 24, ... ? (indice : chaque terme double)", en: "Sequence: 3, 6, 12, 24, ... ? (hint: each term doubles)" },
    options: [
      { fr: "48", en: "48" },
      { fr: "36", en: "36" },
      { fr: "54", en: "54" },
    ],
    correctIndex: 0,
    hint: { fr: "Double le dernier nombre de la suite (24).", en: "Double the last number in the sequence (24)." },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque terme est le double du précédent : 24 x 2 = 48.", en: "Each term is double the previous one: 24 x 2 = 48." },
  },
  {
    id: "cha-log-6",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Dans un mini-tournoi, l'équipe A bat l'équipe B, l'équipe C bat l'équipe D, puis A bat C. Combien de victoires l'équipe A a-t-elle en tout ?", en: "In a mini tournament, team A beats team B, team C beats team D, then A beats C. How many total wins does team A have?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "3", en: "3" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte chaque match gagné par l'équipe A, un par un.", en: "Count each match won by team A, one by one." },
    strategyId: "compter-organise",
    explanation: { fr: "A gagne contre B, puis A gagne contre C : cela fait 2 victoires pour A.", en: "A beats B, then A beats C: that's 2 wins for A." },
  },
  {
    id: "cha-log-7",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Complète la suite : 2, 3, 5, 8, 13, ... ? (indice : additionne les deux termes précédents)", en: "Complete the sequence: 2, 3, 5, 8, 13, ... ? (hint: add the two previous terms)" },
    options: [
      { fr: "21", en: "21" },
      { fr: "20", en: "20" },
      { fr: "22", en: "22" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne les deux derniers nombres : 8 + 13.", en: "Add the last two numbers: 8 + 13." },
    strategyId: "chercher-motif",
    explanation: { fr: "8 + 13 = 21.", en: "8 + 13 = 21." },
  },
  {
    id: "cha-log-8",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Sur une île, les chevaliers disent toujours la vérité et les fripons mentent toujours. Un habitant dit : 'Je suis un chevalier ou un fripon.' Est-ce vrai ?", en: "On an island, knights always tell the truth and knaves always lie. An islander says: 'I am a knight or a knave.' Is this true?" },
    options: [
      { fr: "Toujours vrai, car c'est forcément l'un ou l'autre", en: "Always true, since it must be one or the other" },
      { fr: "Toujours faux", en: "Always false" },
      { fr: "Impossible à savoir", en: "Impossible to know" },
    ],
    correctIndex: 0,
    hint: { fr: "Sur cette île, chaque habitant est forcément soit un chevalier, soit un fripon.", en: "On this island, every islander is necessarily either a knight or a knave." },
    strategyId: "essai-organise",
    explanation: { fr: "Comme chaque habitant est soit un chevalier soit un fripon, la phrase 'je suis l'un ou l'autre' est toujours vraie, peu importe qui la dit.", en: "Since every islander is either a knight or a knave, the statement 'I am one or the other' is always true, no matter who says it." },
  },

  // Calcul
  {
    id: "cha-cal-5",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Calcule astucieusement : 199 x 3. Astuce : 199 c'est presque 200.", en: "Calculate cleverly: 199 x 3. Hint: 199 is almost 200." },
    options: [
      { fr: "597", en: "597" },
      { fr: "594", en: "594" },
      { fr: "600", en: "600" },
    ],
    correctIndex: 0,
    hint: { fr: "Remplace 199 par 200, multiplie, puis enlève 3 (un 1 par 199 remplacé).", en: "Replace 199 with 200, multiply, then subtract 3 (one 1 for each 199 replaced)." },
    strategyId: "petits-cas",
    explanation: { fr: "200 x 3 = 600. Comme on a ajouté 1 de trop à chacun des 3 groupes, on enlève 3 : 600 - 3 = 597.", en: "200 x 3 = 600. Since we added 1 too many in each of the 3 groups, we subtract 3: 600 - 3 = 597." },
  },
  {
    id: "cha-cal-6",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "La somme de quatre nombres pairs consécutifs est 44. Quel est le plus petit ?", en: "The sum of four consecutive even numbers is 44. What is the smallest one?" },
    options: [
      { fr: "8", en: "8" },
      { fr: "6", en: "6" },
      { fr: "10", en: "10" },
    ],
    correctIndex: 0,
    hint: { fr: "Si le plus petit est n, les nombres sont n, n+2, n+4, n+6. Additionne-les et résous.", en: "If the smallest is n, the numbers are n, n+2, n+4, n+6. Add them up and solve." },
    strategyId: "essai-organise",
    explanation: { fr: "En essayant 8 : 8 + 10 + 12 + 14 = 44. Le plus petit nombre est donc 8.", en: "Trying 8: 8 + 10 + 12 + 14 = 44. So the smallest number is 8." },
  },
  {
    id: "cha-cal-7",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Un nombre multiplié par lui-même donne 169. Quel est ce nombre ?", en: "A number multiplied by itself gives 169. What is that number?" },
    options: [
      { fr: "13", en: "13" },
      { fr: "12", en: "12" },
      { fr: "14", en: "14" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie quelques nombres proches de 12 et calcule leur carré.", en: "Try a few numbers close to 12 and calculate their square." },
    strategyId: "essai-organise",
    explanation: { fr: "13 x 13 = 169.", en: "13 x 13 = 169." },
  },
  {
    id: "cha-cal-8",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Combien y a-t-il de multiples de 9 entre 1 et 100 ?", en: "How many multiples of 9 are there between 1 and 100?" },
    options: [
      { fr: "11", en: "11" },
      { fr: "10", en: "10" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Liste les multiples de 9 un par un jusqu'à dépasser 100.", en: "List the multiples of 9 one by one until you go past 100." },
    strategyId: "compter-organise",
    explanation: { fr: "9, 18, 27, ..., 99 : cela fait 11 multiples de 9 entre 1 et 100.", en: "9, 18, 27, ..., 99: that's 11 multiples of 9 between 1 and 100." },
  },

  // Geometrie
  {
    id: "cha-geo-5",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un triangle a un angle droit (90°) et un autre angle de 30°. Quel est le troisième angle ?", en: "A triangle has a right angle (90°) and another angle of 30°. What is the third angle?" },
    options: [
      { fr: "60°", en: "60°" },
      { fr: "50°", en: "50°" },
      { fr: "70°", en: "70°" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne les deux angles connus, puis soustrais le total à 180°.", en: "Add the two known angles, then subtract the total from 180°." },
    strategyId: "a-rebours",
    explanation: { fr: "90 + 30 = 120°. 180 - 120 = 60°.", en: "90 + 30 = 120°. 180 - 120 = 60°." },
  },
  {
    id: "cha-geo-6",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un cercle a un rayon de 5 cm. Quel est son diamètre ?", en: "A circle has a radius of 5 cm. What is its diameter?" },
    options: [
      { fr: "10 cm", en: "10 cm" },
      { fr: "15 cm", en: "15 cm" },
      { fr: "5 cm", en: "5 cm" },
    ],
    correctIndex: 0,
    hint: { fr: "Le diamètre est toujours le double du rayon.", en: "The diameter is always double the radius." },
    strategyId: "chercher-motif",
    explanation: { fr: "5 x 2 = 10 cm.", en: "5 x 2 = 10 cm." },
  },
  {
    id: "cha-geo-7",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un rectangle a une longueur double de sa largeur. Si sa largeur est 4 cm, quelle est son aire ?", en: "A rectangle's length is double its width. If its width is 4 cm, what is its area?" },
    options: [
      { fr: "32 cm²", en: "32 cm²" },
      { fr: "16 cm²", en: "16 cm²" },
      { fr: "24 cm²", en: "24 cm²" },
    ],
    correctIndex: 0,
    hint: { fr: "Trouve d'abord la longueur (le double de 4), puis calcule l'aire.", en: "First find the length (double 4), then calculate the area." },
    strategyId: "petits-cas",
    explanation: { fr: "La longueur est 4 x 2 = 8 cm. L'aire est 8 x 4 = 32 cm².", en: "The length is 4 x 2 = 8 cm. The area is 8 x 4 = 32 cm²." },
  },
  {
    id: "cha-geo-8",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Combien de faces a un cube ?", en: "How many faces does a cube have?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "4", en: "4" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Imagine un dé à jouer : combien de faces peux-tu voir au total ?", en: "Imagine a dice: how many faces does it have in total?" },
    strategyId: "dessiner",
    explanation: { fr: "Un cube a 6 faces carrées identiques, comme un dé.", en: "A cube has 6 identical square faces, like a dice." },
  },

  // Combinatoire
  {
    id: "cha-com-5",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien d'anagrammes (réarrangements) peux-tu faire avec les 3 lettres A, B, C, toutes différentes ?", en: "How many anagrams (rearrangements) can you make with the 3 different letters A, B, C?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "3", en: "3" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour la première lettre il y a 3 choix, puis 2, puis 1 : multiplie ces nombres.", en: "For the first letter there are 3 choices, then 2, then 1: multiply these numbers." },
    strategyId: "essai-organise",
    explanation: { fr: "3 x 2 x 1 = 6.", en: "3 x 2 x 1 = 6." },
  },
  {
    id: "cha-com-6",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Dans un tournoi de 6 équipes où chaque équipe affronte chaque autre équipe une seule fois, combien de matchs y a-t-il au total ?", en: "In a tournament of 6 teams where every team plays every other team exactly once, how many matches are there in total?" },
    options: [
      { fr: "15", en: "15" },
      { fr: "12", en: "12" },
      { fr: "30", en: "30" },
    ],
    correctIndex: 0,
    hint: { fr: "Chaque équipe joue contre 5 autres, mais chaque match est compté deux fois : divise par 2.", en: "Each team plays 5 others, but each match gets counted twice: divide by 2." },
    strategyId: "compter-organise",
    explanation: { fr: "6 équipes x 5 matchs chacune = 30, mais chaque match est compté deux fois : 30 / 2 = 15.", en: "6 teams x 5 matches each = 30, but each match is counted twice: 30 / 2 = 15." },
  },
  {
    id: "cha-com-7",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de codes à 3 chiffres peux-tu former avec les chiffres 1 à 5, en pouvant répéter les chiffres ?", en: "How many 3-digit codes can you form with the digits 1 to 5, allowing repeated digits?" },
    options: [
      { fr: "125", en: "125" },
      { fr: "60", en: "60" },
      { fr: "15", en: "15" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chacune des 3 positions, il y a 5 choix possibles : multiplie ces nombres.", en: "For each of the 3 positions, there are 5 possible choices: multiply these numbers." },
    strategyId: "essai-organise",
    explanation: { fr: "5 x 5 x 5 = 125.", en: "5 x 5 x 5 = 125." },
  },
  {
    id: "cha-com-8",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons peux-tu choisir 3 livres parmi 5 pour les emporter en vacances ?", en: "How many ways can you choose 3 books out of 5 to bring on vacation?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "15", en: "15" },
      { fr: "20", en: "20" },
    ],
    correctIndex: 0,
    hint: { fr: "Choisir 3 livres parmi 5, c'est la même chose que choisir les 2 qu'on laisse à la maison.", en: "Choosing 3 books out of 5 is the same as choosing the 2 you leave at home." },
    strategyId: "compter-organise",
    explanation: { fr: "Choisir 3 parmi 5 revient à choisir 2 à laisser de côté : il y a 10 façons de le faire (comme choisir 2 fruits parmi 5).", en: "Choosing 3 out of 5 is the same as choosing 2 to leave aside: there are 10 ways to do it (like choosing 2 fruits out of 5)." },
  },
];

export function getProblemsForTier(tier: Tier): Problem[] {
  return PROBLEMS.filter((problem) => problem.tier === tier);
}

export function getProblemsForTierAndDomain(tier: Tier, domain: Domain): Problem[] {
  return PROBLEMS.filter((problem) => problem.tier === tier && problem.domain === domain);
}

export function shuffleProblemOptions(problem: Problem): Problem {
  const order = shuffle(problem.options.map((_, i) => i));
  const options = order.map((i) => problem.options[i]);
  const correctIndex = order.indexOf(problem.correctIndex);
  return { ...problem, options, correctIndex };
}
