import type { Tier } from "../profiles";
import type { Domain } from "../domains";
import type { StrategyId } from "../strategies";

export type LocalizedText = { fr: string; en: string };

export type Problem = {
  id: string;
  tier: Tier;
  domain: Domain;
  prompt: LocalizedText;
  options: LocalizedText[];
  correctIndex: number;
  hint: LocalizedText;
  strategyId: StrategyId;
  explanation: LocalizedText;
};

export const PROBLEMS: Problem[] = [
  // ===== ECLAIREUR (6 ans) =====

  // Logique
  {
    id: "ecl-log-1",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Rouge, Bleu, Rouge, Bleu, Rouge, ... Quelle est la couleur suivante ?", en: "Red, Blue, Red, Blue, Red, ... What color comes next?" },
    options: [
      { fr: "Bleu", en: "Blue" },
      { fr: "Rouge", en: "Red" },
      { fr: "Vert", en: "Green" },
    ],
    correctIndex: 0,
    hint: { fr: "Regarde comment les couleurs alternent, une par une.", en: "Look at how the colors alternate, one by one." },
    strategyId: "chercher-motif",
    explanation: { fr: "Les couleurs alternent : Rouge, Bleu, Rouge, Bleu... Après Rouge vient toujours Bleu.", en: "The colors alternate: Red, Blue, Red, Blue... After Red always comes Blue." },
  },
  {
    id: "ecl-log-2",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Regarde cette suite de formes : 🔺 🔺 🔷 🔺. Laquelle est différente des autres ?", en: "Look at this sequence of shapes: 🔺 🔺 🔷 🔺. Which one is different from the others?" },
    options: [
      { fr: "La 1ère", en: "The 1st" },
      { fr: "La 2ème", en: "The 2nd" },
      { fr: "La 3ème", en: "The 3rd" },
    ],
    correctIndex: 2,
    hint: { fr: "Compare chaque forme aux autres, une par une.", en: "Compare each shape to the others, one by one." },
    strategyId: "dessiner",
    explanation: { fr: "Les 1ère, 2ème et 4ème formes sont des triangles. La 3ème est un losange : c'est elle qui est différente.", en: "The 1st, 2nd and 4th shapes are triangles. The 3rd is a diamond: that's the different one." },
  },
  {
    id: "ecl-log-3",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Léo a plus de billes que Zoé. Zoé a plus de billes que Tom. Qui a le moins de billes ?", en: "Léo has more marbles than Zoé. Zoé has more marbles than Tom. Who has the fewest marbles?" },
    options: [
      { fr: "Tom", en: "Tom" },
      { fr: "Zoé", en: "Zoé" },
      { fr: "Léo", en: "Léo" },
    ],
    correctIndex: 0,
    hint: { fr: "Range les trois amis du plus petit nombre de billes au plus grand.", en: "Sort the three friends from the fewest marbles to the most." },
    strategyId: "dessiner",
    explanation: { fr: "Léo a plus que Zoé, et Zoé a plus que Tom. Dans l'ordre : Tom, puis Zoé, puis Léo. Tom en a donc le moins.", en: "Léo has more than Zoé, and Zoé has more than Tom. In order: Tom, then Zoé, then Léo. So Tom has the fewest." },
  },
  {
    id: "ecl-log-4",
    tier: "eclaireur",
    domain: "logique",
    prompt: { fr: "Un motif se répète : ⭐️ ⭐️ 🌙 ⭐️ ⭐️ 🌙 ... Quel symbole est le 6ème ?", en: "A pattern repeats: ⭐️ ⭐️ 🌙 ⭐️ ⭐️ 🌙 ... What is the 6th symbol?" },
    options: [
      { fr: "⭐️", en: "⭐️" },
      { fr: "🌙", en: "🌙" },
      { fr: "❓", en: "❓" },
    ],
    correctIndex: 1,
    hint: { fr: "Le motif se répète toutes les 3 cases : compte par groupes de 3.", en: "The pattern repeats every 3 spots: count in groups of 3." },
    strategyId: "chercher-motif",
    explanation: { fr: "Le motif ⭐️⭐️🌙 fait 3 symboles. La 6ème case termine le 2ème groupe de 3 : c'est donc 🌙.", en: "The pattern ⭐️⭐️🌙 is 3 symbols long. Spot 6 ends the 2nd group of 3: so it's 🌙." },
  },

  // Calcul
  {
    id: "ecl-cal-1",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Combien font 9 + 9 ? Astuce : pense à 10 + 10.", en: "What is 9 + 9? Hint: think of 10 + 10." },
    options: [
      { fr: "18", en: "18" },
      { fr: "20", en: "20" },
      { fr: "16", en: "16" },
    ],
    correctIndex: 0,
    hint: { fr: "10 + 10 = 20. Mais 9 c'est un peu moins que 10... enlève 2 au total.", en: "10 + 10 = 20. But 9 is a bit less than 10... take 2 off the total." },
    strategyId: "petits-cas",
    explanation: { fr: "10 + 10 = 20, mais chaque 9 est 1 de moins que 10, donc on enlève 1 pour chaque nombre : 20 - 2 = 18.", en: "10 + 10 = 20, but each 9 is 1 less than 10, so we remove 1 for each number: 20 - 2 = 18." },
  },
  {
    id: "ecl-cal-2",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Il y a 5 pommes dans un panier. On en ajoute 5. Puis on en enlève 2. Combien reste-t-il de pommes ?", en: "There are 5 apples in a basket. 5 more are added. Then 2 are removed. How many apples are left?" },
    options: [
      { fr: "8", en: "8" },
      { fr: "10", en: "10" },
      { fr: "7", en: "7" },
    ],
    correctIndex: 0,
    hint: { fr: "Fais les étapes l'une après l'autre : d'abord additionne, puis soustrais.", en: "Do the steps one after another: first add, then subtract." },
    strategyId: "dessiner",
    explanation: { fr: "5 + 5 = 10, puis 10 - 2 = 8. Il reste 8 pommes.", en: "5 + 5 = 10, then 10 - 2 = 8. There are 8 apples left." },
  },
  {
    id: "ecl-cal-3",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Trouve le nombre manquant : 3 + ? = 7", en: "Find the missing number: 3 + ? = 7" },
    options: [
      { fr: "4", en: "4" },
      { fr: "3", en: "3" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à l'opération inverse : 7 - 3.", en: "Think of the opposite operation: 7 - 3." },
    strategyId: "a-rebours",
    explanation: { fr: "7 - 3 = 4, donc le nombre manquant est 4. On vérifie : 3 + 4 = 7.", en: "7 - 3 = 4, so the missing number is 4. Check: 3 + 4 = 7." },
  },
  {
    id: "ecl-cal-4",
    tier: "eclaireur",
    domain: "calcul",
    prompt: { fr: "Sans compter un par un : combien y a-t-il de doigts sur 2 mains ?", en: "Without counting one by one: how many fingers are on 2 hands?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "8", en: "8" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Une main a 5 doigts. Imagine additionner 5 deux fois.", en: "One hand has 5 fingers. Imagine adding 5 twice." },
    strategyId: "chercher-motif",
    explanation: { fr: "Une main a 5 doigts, donc deux mains ont 5 + 5 = 10 doigts.", en: "One hand has 5 fingers, so two hands have 5 + 5 = 10 fingers." },
  },

  // Geometrie
  {
    id: "ecl-geo-1",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Combien de côtés a un carré ?", en: "How many sides does a square have?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "3", en: "3" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte les côtés un par un en suivant le contour de la forme.", en: "Count the sides one by one, following the outline of the shape." },
    strategyId: "dessiner",
    explanation: { fr: "Un carré a 4 côtés tous égaux.", en: "A square has 4 sides, all equal." },
  },
  {
    id: "ecl-geo-2",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Quelle forme n'a pas de coins (de sommets) ?", en: "Which shape has no corners at all?" },
    options: [
      { fr: "Le cercle", en: "The circle" },
      { fr: "Le carré", en: "The square" },
      { fr: "Le triangle", en: "The triangle" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à une forme toute ronde, sans aucune pointe.", en: "Think of a shape that's completely round, with no points." },
    strategyId: "dessiner",
    explanation: { fr: "Le cercle est une courbe fermée sans coin : il n'a aucun sommet.", en: "The circle is a closed curve with no corner: it has no vertices at all." },
  },
  {
    id: "ecl-geo-3",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Si tu plies un carré en deux bien au milieu, les deux parties sont-elles pareilles ?", en: "If you fold a square exactly in half, are the two parts the same?" },
    options: [
      { fr: "Oui, elles sont identiques", en: "Yes, they are identical" },
      { fr: "Non, elles sont différentes", en: "No, they are different" },
      { fr: "Ça dépend du jour", en: "It depends on the day" },
    ],
    correctIndex: 0,
    hint: { fr: "C'est ce qu'on appelle la symétrie : les deux moitiés se ressemblent comme un miroir.", en: "This is called symmetry: the two halves look alike, like a mirror." },
    strategyId: "dessiner",
    explanation: { fr: "Un carré plié en son milieu donne deux parties identiques : c'est un axe de symétrie.", en: "A square folded through its middle gives two identical parts: that's a line of symmetry." },
  },
  {
    id: "ecl-geo-4",
    tier: "eclaireur",
    domain: "geometrie",
    prompt: { fr: "Un triangle a combien de sommets (de coins) ?", en: "How many corners (vertices) does a triangle have?" },
    options: [
      { fr: "3", en: "3" },
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte les pointes de la forme, une par une.", en: "Count the points of the shape, one by one." },
    strategyId: "dessiner",
    explanation: { fr: "Un triangle a 3 côtés et donc 3 sommets.", en: "A triangle has 3 sides and therefore 3 vertices." },
  },

  // Combinatoire
  {
    id: "ecl-com-1",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Tu as un tee-shirt rouge et un bleu, et un pantalon noir et un blanc. Combien de tenues différentes peux-tu faire ?", en: "You have a red shirt and a blue one, and black pants and white pants. How many different outfits can you make?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
      { fr: "6", en: "6" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chaque tee-shirt, il y a 2 choix de pantalon possibles.", en: "For each shirt, there are 2 possible pants choices." },
    strategyId: "essai-organise",
    explanation: { fr: "2 tee-shirts x 2 pantalons = 4 tenues : rouge-noir, rouge-blanc, bleu-noir, bleu-blanc.", en: "2 shirts x 2 pants = 4 outfits: red-black, red-white, blue-black, blue-white." },
  },
  {
    id: "ecl-com-2",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons peux-tu ranger une balle et une poupée, l'une à côté de l'autre sur une étagère ?", en: "How many ways can you arrange a ball and a doll, side by side on a shelf?" },
    options: [
      { fr: "2", en: "2" },
      { fr: "1", en: "1" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie toutes les positions possibles, une par une.", en: "Try all possible positions, one by one." },
    strategyId: "essai-organise",
    explanation: { fr: "Soit la balle est à gauche et la poupée à droite, soit l'inverse : ça fait 2 façons.", en: "Either the ball is on the left and the doll on the right, or the opposite: that's 2 ways." },
  },
  {
    id: "ecl-com-3",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 3 bonbons de couleurs différentes. Combien de façons peux-tu en choisir 1 seul à manger ?", en: "You have 3 differently colored candies. In how many ways can you choose just 1 to eat?" },
    options: [
      { fr: "3", en: "3" },
      { fr: "1", en: "1" },
      { fr: "6", en: "6" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre de bonbons disponibles.", en: "Just count the number of available candies." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 3 bonbons, donc 3 choix possibles.", en: "There are 3 candies, so 3 possible choices." },
  },
  {
    id: "ecl-com-4",
    tier: "eclaireur",
    domain: "combinatoire",
    prompt: { fr: "Léo a 2 chapeaux et 3 paires de lunettes. Combien de looks différents peut-il faire (un chapeau + une paire de lunettes) ?", en: "Léo has 2 hats and 3 pairs of glasses. How many different looks can he make (one hat + one pair of glasses)?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "5", en: "5" },
      { fr: "3", en: "3" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chaque chapeau, compte le nombre de lunettes possibles.", en: "For each hat, count the possible glasses." },
    strategyId: "essai-organise",
    explanation: { fr: "2 chapeaux x 3 paires de lunettes = 6 looks différents.", en: "2 hats x 3 pairs of glasses = 6 different looks." },
  },

  // ===== CHERCHEUR (8 ans) =====

  // Logique
  {
    id: "che-log-1",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Complète la suite : 2, 4, 6, 8, ... ?", en: "Complete the sequence: 2, 4, 6, 8, ... ?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "9", en: "9" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Chaque nombre augmente-t-il toujours de la même quantité ?", en: "Does each number always increase by the same amount?" },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque nombre augmente de 2 : 2, 4, 6, 8, 10.", en: "Each number increases by 2: 2, 4, 6, 8, 10." },
  },
  {
    id: "che-log-2",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Léa, Max et Nina ont chacun un animal différent : chat, chien, poisson. Léa n'a pas de chat. Max n'a pas de poisson. Nina a un chien. Qui a le chat ?", en: "Léa, Max and Nina each have a different pet: cat, dog, fish. Léa doesn't have a cat. Max doesn't have a fish. Nina has a dog. Who has the cat?" },
    options: [
      { fr: "Léa", en: "Léa" },
      { fr: "Max", en: "Max" },
      { fr: "Nina", en: "Nina" },
    ],
    correctIndex: 1,
    hint: { fr: "Élimine les possibilités une par une grâce aux indices.", en: "Eliminate the possibilities one by one using the clues." },
    strategyId: "essai-organise",
    explanation: { fr: "Nina a le chien. Léa n'a pas le chat, donc Léa a le poisson. Il reste le chat pour Max.", en: "Nina has the dog. Léa doesn't have the cat, so Léa has the fish. That leaves the cat for Max." },
  },
  {
    id: "che-log-3",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Complète : 1, 1, 2, 3, 5, ... ? (indice : additionne les deux nombres précédents)", en: "Complete: 1, 1, 2, 3, 5, ... ? (hint: add the two previous numbers)" },
    options: [
      { fr: "8", en: "8" },
      { fr: "7", en: "7" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne les deux derniers nombres de la suite : 3 + 5.", en: "Add the last two numbers of the sequence: 3 + 5." },
    strategyId: "chercher-motif",
    explanation: { fr: "Chaque nombre est la somme des deux précédents : 3 + 5 = 8.", en: "Each number is the sum of the two before it: 3 + 5 = 8." },
  },
  {
    id: "che-log-4",
    tier: "chercheur",
    domain: "logique",
    prompt: { fr: "Dans une course, Emma arrive avant Karim. Karim arrive avant Lina. Qui arrive en dernier ?", en: "In a race, Emma finishes before Karim. Karim finishes before Lina. Who finishes last?" },
    options: [
      { fr: "Lina", en: "Lina" },
      { fr: "Emma", en: "Emma" },
      { fr: "Karim", en: "Karim" },
    ],
    correctIndex: 0,
    hint: { fr: "Range les trois coureurs dans l'ordre d'arrivée, du premier au dernier.", en: "Sort the three runners in finishing order, first to last." },
    strategyId: "dessiner",
    explanation: { fr: "Emma avant Karim, Karim avant Lina : l'ordre est Emma, Karim, Lina. Lina arrive donc en dernier.", en: "Emma before Karim, Karim before Lina: the order is Emma, Karim, Lina. So Lina finishes last." },
  },

  // Calcul
  {
    id: "che-cal-1",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Calcule astucieusement : 25 + 19. Astuce : 19 c'est presque 20.", en: "Calculate cleverly: 25 + 19. Hint: 19 is almost 20." },
    options: [
      { fr: "44", en: "44" },
      { fr: "45", en: "45" },
      { fr: "43", en: "43" },
    ],
    correctIndex: 0,
    hint: { fr: "Remplace 19 par 20, additionne, puis enlève 1 au résultat.", en: "Replace 19 with 20, add, then subtract 1 from the result." },
    strategyId: "petits-cas",
    explanation: { fr: "25 + 20 = 45. Comme on a ajouté 1 de trop (20 au lieu de 19), on enlève 1 : 45 - 1 = 44.", en: "25 + 20 = 45. Since we added 1 too many (20 instead of 19), we subtract 1: 45 - 1 = 44." },
  },
  {
    id: "che-cal-2",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Un cahier coûte 3 euros. Combien coûtent 4 cahiers ?", en: "A notebook costs 3 euros. How much do 4 notebooks cost?" },
    options: [
      { fr: "12", en: "12" },
      { fr: "9", en: "9" },
      { fr: "16", en: "16" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne 3 quatre fois, ou multiplie 3 par 4.", en: "Add 3 four times, or multiply 3 by 4." },
    strategyId: "chercher-motif",
    explanation: { fr: "3 x 4 = 12 euros.", en: "3 x 4 = 12 euros." },
  },
  {
    id: "che-cal-3",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Trouve le nombre manquant : ? x 5 = 35", en: "Find the missing number: ? x 5 = 35" },
    options: [
      { fr: "7", en: "7" },
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Pense à la table de multiplication de 5.", en: "Think of the 5 times table." },
    strategyId: "a-rebours",
    explanation: { fr: "5 x 7 = 35, donc le nombre manquant est 7.", en: "5 x 7 = 35, so the missing number is 7." },
  },
  {
    id: "che-cal-4",
    tier: "chercheur",
    domain: "calcul",
    prompt: { fr: "Sarah avait des billes. Elle en a gagné 12, puis elle en a perdu 5. Elle en a maintenant 20. Combien en avait-elle au départ ?", en: "Sarah had marbles. She won 12, then lost 5. She now has 20. How many did she have at the start?" },
    options: [
      { fr: "13", en: "13" },
      { fr: "17", en: "17" },
      { fr: "7", en: "7" },
    ],
    correctIndex: 0,
    hint: { fr: "Pars du résultat final (20) et fais les opérations inverses, dans l'ordre inverse.", en: "Start from the final result (20) and do the opposite operations, in reverse order." },
    strategyId: "a-rebours",
    explanation: { fr: "En partant de 20 : on annule la perte de 5 (20 + 5 = 25), puis on annule le gain de 12 (25 - 12 = 13).", en: "Starting from 20: undo the loss of 5 (20 + 5 = 25), then undo the gain of 12 (25 - 12 = 13)." },
  },

  // Geometrie
  {
    id: "che-geo-1",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Un rectangle mesure 5 cm de long et 3 cm de large. Quel est son périmètre ?", en: "A rectangle is 5 cm long and 3 cm wide. What is its perimeter?" },
    options: [
      { fr: "16 cm", en: "16 cm" },
      { fr: "15 cm", en: "15 cm" },
      { fr: "8 cm", en: "8 cm" },
    ],
    correctIndex: 0,
    hint: { fr: "Le périmètre, c'est le tour de la forme : additionne tous les côtés.", en: "The perimeter is the distance around the shape: add up all the sides." },
    strategyId: "dessiner",
    explanation: { fr: "Un rectangle a 2 longueurs et 2 largeurs : 5 + 5 + 3 + 3 = 16 cm.", en: "A rectangle has 2 lengths and 2 widths: 5 + 5 + 3 + 3 = 16 cm." },
  },
  {
    id: "che-geo-2",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Combien de côtés a un hexagone ?", en: "How many sides does a hexagon have?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "5", en: "5" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Le préfixe 'hexa' veut dire six.", en: "The prefix 'hexa' means six." },
    strategyId: "dessiner",
    explanation: { fr: "Un hexagone a 6 côtés.", en: "A hexagon has 6 sides." },
  },
  {
    id: "che-geo-3",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Une figure a un axe de symétrie vertical. Si tu la plies en deux le long de cet axe, que se passe-t-il ?", en: "A figure has a vertical line of symmetry. If you fold it in half along that line, what happens?" },
    options: [
      { fr: "Les deux moitiés se superposent exactement", en: "The two halves overlap exactly" },
      { fr: "Les deux moitiés sont différentes", en: "The two halves are different" },
      { fr: "Rien de particulier", en: "Nothing in particular" },
    ],
    correctIndex: 0,
    hint: { fr: "La symétrie veut dire que les deux parties sont comme un miroir l'une de l'autre.", en: "Symmetry means the two parts are like a mirror of each other." },
    strategyId: "dessiner",
    explanation: { fr: "Par définition, un axe de symétrie sépare une figure en deux parties qui se superposent parfaitement.", en: "By definition, a line of symmetry splits a figure into two parts that overlap perfectly." },
  },
  {
    id: "che-geo-4",
    tier: "chercheur",
    domain: "geometrie",
    prompt: { fr: "Un carré a un côté de 4 cm. Quelle est son aire ?", en: "A square has a side of 4 cm. What is its area?" },
    options: [
      { fr: "16 cm²", en: "16 cm²" },
      { fr: "8 cm²", en: "8 cm²" },
      { fr: "12 cm²", en: "12 cm²" },
    ],
    correctIndex: 0,
    hint: { fr: "L'aire d'un carré, c'est le côté multiplié par lui-même.", en: "The area of a square is the side multiplied by itself." },
    strategyId: "petits-cas",
    explanation: { fr: "4 x 4 = 16 cm².", en: "4 x 4 = 16 cm²." },
  },

  // Combinatoire
  {
    id: "che-com-1",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Tu as 3 t-shirts et 2 shorts. Combien de tenues différentes peux-tu former ?", en: "You have 3 t-shirts and 2 shorts. How many different outfits can you form?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "5", en: "5" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour chaque t-shirt, compte le nombre de shorts possibles, puis additionne.", en: "For each t-shirt, count the possible shorts, then add them up." },
    strategyId: "essai-organise",
    explanation: { fr: "3 t-shirts x 2 shorts = 6 tenues différentes.", en: "3 t-shirts x 2 shorts = 6 different outfits." },
  },
  {
    id: "che-com-2",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Combien de nombres à 2 chiffres peux-tu former avec les chiffres 1, 2 et 3, sans répéter de chiffre ?", en: "How many 2-digit numbers can you form with the digits 1, 2 and 3, without repeating a digit?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "9", en: "9" },
      { fr: "3", en: "3" },
    ],
    correctIndex: 0,
    hint: { fr: "Écris toutes les possibilités dans un ordre organisé pour ne pas te tromper.", en: "Write out all the possibilities in an organized order so you don't make mistakes." },
    strategyId: "compter-organise",
    explanation: { fr: "Les possibilités sont : 12, 13, 21, 23, 31, 32. Cela fait 6 nombres.", en: "The possibilities are: 12, 13, 21, 23, 31, 32. That's 6 numbers." },
  },
  {
    id: "che-com-3",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Dans une classe, il y a 4 équipes possibles pour un jeu. Chaque enfant doit choisir une équipe. Combien de choix possibles as-tu ?", en: "In a class, there are 4 possible teams for a game. Each child must choose a team. How many possible choices do you have?" },
    options: [
      { fr: "4", en: "4" },
      { fr: "2", en: "2" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Compte simplement le nombre d'équipes disponibles.", en: "Just count the number of available teams." },
    strategyId: "compter-organise",
    explanation: { fr: "Il y a 4 équipes, donc 4 choix possibles.", en: "There are 4 teams, so 4 possible choices." },
  },
  {
    id: "che-com-4",
    tier: "chercheur",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons différentes peux-tu ranger 3 livres A, B, C côte à côte sur une étagère ?", en: "How many different ways can you arrange 3 books A, B, C side by side on a shelf?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "3", en: "3" },
      { fr: "9", en: "9" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie toutes les combinaisons en commençant par chaque livre à tour de rôle.", en: "Try all combinations by starting with each book in turn." },
    strategyId: "essai-organise",
    explanation: { fr: "Il y a 3 choix pour le premier livre, puis 2 pour le second, puis 1 pour le dernier : 3 x 2 x 1 = 6.", en: "There are 3 choices for the first book, then 2 for the second, then 1 for the last: 3 x 2 x 1 = 6." },
  },

  // ===== CHAMPION (11 ans) =====

  // Logique
  {
    id: "cha-log-1",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Quatre amis (Ana, Ben, Cléo, Dan) sont classés à une course. Ana n'est pas 1ère ni dernière. Ben arrive juste après Ana. Dan est 1er. Cléo est dernière. Quel est le classement complet ?", en: "Four friends (Ana, Ben, Cléo, Dan) are ranked in a race. Ana is neither 1st nor last. Ben finishes right after Ana. Dan is 1st. Cléo is last. What is the full ranking?" },
    options: [
      { fr: "Dan, Ana, Ben, Cléo", en: "Dan, Ana, Ben, Cléo" },
      { fr: "Dan, Ben, Ana, Cléo", en: "Dan, Ben, Ana, Cléo" },
      { fr: "Ana, Dan, Ben, Cléo", en: "Ana, Dan, Ben, Cléo" },
    ],
    correctIndex: 0,
    hint: { fr: "Place d'abord ceux dont la position est certaine (Dan et Cléo), puis déduis le reste.", en: "Place first the ones whose position is certain (Dan and Cléo), then deduce the rest." },
    strategyId: "essai-organise",
    explanation: { fr: "Dan est 1er et Cléo est 4ème. Ana n'est ni 1ère ni dernière, donc elle est 2ème ou 3ème. Ben arrive juste après Ana : si Ana était 3ème, Ben serait 4ème, ce qui est la place de Cléo. Donc Ana est 2ème et Ben 3ème.", en: "Dan is 1st and Cléo is 4th. Ana is neither 1st nor last, so she is 2nd or 3rd. Ben finishes right after Ana: if Ana were 3rd, Ben would be 4th, which is Cléo's spot. So Ana is 2nd and Ben is 3rd." },
  },
  {
    id: "cha-log-2",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Suite logique : 1, 4, 9, 16, 25, ... ? (indice : ce sont des carrés parfaits)", en: "Logical sequence: 1, 4, 9, 16, 25, ... ? (hint: these are perfect squares)" },
    options: [
      { fr: "36", en: "36" },
      { fr: "30", en: "30" },
      { fr: "35", en: "35" },
    ],
    correctIndex: 0,
    hint: { fr: "Ce sont les carrés de 1, 2, 3, 4, 5... Quel est le carré de 6 ?", en: "These are the squares of 1, 2, 3, 4, 5... What is the square of 6?" },
    strategyId: "chercher-motif",
    explanation: { fr: "Les termes sont 1², 2², 3², 4², 5², donc le suivant est 6² = 36.", en: "The terms are 1², 2², 3², 4², 5², so the next one is 6² = 36." },
  },
  {
    id: "cha-log-3",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Un menteur ment toujours, un honnête dit toujours la vérité. Un enfant affirme : 'Je suis un menteur.' Est-ce possible ?", en: "A liar always lies, an honest person always tells the truth. A child says: 'I am a liar.' Is this possible?" },
    options: [
      { fr: "Non, c'est impossible (contradiction)", en: "No, it's impossible (a contradiction)" },
      { fr: "Oui, c'est forcément un menteur", en: "Yes, it must be a liar" },
      { fr: "Oui, c'est forcément un honnête", en: "Yes, it must be honest" },
    ],
    correctIndex: 0,
    hint: { fr: "Teste les deux hypothèses (menteur, honnête) une par une et regarde si elles tiennent debout.", en: "Test both hypotheses (liar, honest) one by one and see if they hold up." },
    strategyId: "essai-organise",
    explanation: { fr: "Si c'était un honnête, il dirait la vérité, donc il serait un menteur : contradiction. Si c'était un menteur, sa phrase serait un mensonge, donc il serait honnête : contradiction aussi. La phrase est donc impossible.", en: "If honest, they'd be telling the truth, so they'd be a liar: contradiction. If a liar, the statement would be a lie, so they'd be honest: also a contradiction. So the statement is impossible." },
  },
  {
    id: "cha-log-4",
    tier: "champion",
    domain: "logique",
    prompt: { fr: "Dans une suite, chaque terme est le double du précédent moins 1 : 2, 3, 5, 9, ... ?", en: "In a sequence, each term is double the previous one minus 1: 2, 3, 5, 9, ... ?" },
    options: [
      { fr: "17", en: "17" },
      { fr: "16", en: "16" },
      { fr: "18", en: "18" },
    ],
    correctIndex: 0,
    hint: { fr: "Applique la règle 'double moins 1' au dernier nombre de la suite (9).", en: "Apply the 'double minus 1' rule to the last number in the sequence (9)." },
    strategyId: "chercher-motif",
    explanation: { fr: "9 x 2 - 1 = 17.", en: "9 x 2 - 1 = 17." },
  },

  // Calcul
  {
    id: "cha-cal-1",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Calcule astucieusement : 99 x 4. Astuce : 99 c'est presque 100.", en: "Calculate cleverly: 99 x 4. Hint: 99 is almost 100." },
    options: [
      { fr: "396", en: "396" },
      { fr: "392", en: "392" },
      { fr: "400", en: "400" },
    ],
    correctIndex: 0,
    hint: { fr: "Remplace 99 par 100, multiplie, puis enlève 4 (un 4 par 99 remplacé).", en: "Replace 99 with 100, multiply, then subtract 4 (one 4 for the 99 replaced)." },
    strategyId: "petits-cas",
    explanation: { fr: "100 x 4 = 400. Comme on a ajouté 1 de trop à chacun des 4 groupes, on enlève 4 : 400 - 4 = 396.", en: "100 x 4 = 400. Since we added 1 too many in each of the 4 groups, we subtract 4: 400 - 4 = 396." },
  },
  {
    id: "cha-cal-2",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "La somme de trois nombres entiers consécutifs est 45. Quel est le nombre du milieu ?", en: "The sum of three consecutive whole numbers is 45. What is the middle number?" },
    options: [
      { fr: "15", en: "15" },
      { fr: "14", en: "14" },
      { fr: "16", en: "16" },
    ],
    correctIndex: 0,
    hint: { fr: "La somme de trois nombres consécutifs vaut toujours 3 fois le nombre du milieu.", en: "The sum of three consecutive numbers is always 3 times the middle number." },
    strategyId: "a-rebours",
    explanation: { fr: "45 / 3 = 15. On vérifie : 14 + 15 + 16 = 45.", en: "45 / 3 = 15. Check: 14 + 15 + 16 = 45." },
  },
  {
    id: "cha-cal-3",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Un nombre multiplié par lui-même donne 144. Quel est ce nombre ?", en: "A number multiplied by itself gives 144. What is that number?" },
    options: [
      { fr: "12", en: "12" },
      { fr: "11", en: "11" },
      { fr: "13", en: "13" },
    ],
    correctIndex: 0,
    hint: { fr: "Essaie quelques nombres proches de 10 et calcule leur carré.", en: "Try a few numbers close to 10 and calculate their square." },
    strategyId: "essai-organise",
    explanation: { fr: "12 x 12 = 144.", en: "12 x 12 = 144." },
  },
  {
    id: "cha-cal-4",
    tier: "champion",
    domain: "calcul",
    prompt: { fr: "Combien y a-t-il de multiples de 7 entre 1 et 50 ?", en: "How many multiples of 7 are there between 1 and 50?" },
    options: [
      { fr: "7", en: "7" },
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
    ],
    correctIndex: 0,
    hint: { fr: "Liste les multiples de 7 un par un jusqu'à dépasser 50.", en: "List the multiples of 7 one by one until you go past 50." },
    strategyId: "compter-organise",
    explanation: { fr: "7, 14, 21, 28, 35, 42, 49 : cela fait 7 multiples de 7 entre 1 et 50.", en: "7, 14, 21, 28, 35, 42, 49: that's 7 multiples of 7 between 1 and 50." },
  },

  // Geometrie
  {
    id: "cha-geo-1",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un rectangle a une aire de 24 cm² et une largeur de 4 cm. Quelle est sa longueur ?", en: "A rectangle has an area of 24 cm² and a width of 4 cm. What is its length?" },
    options: [
      { fr: "6 cm", en: "6 cm" },
      { fr: "8 cm", en: "8 cm" },
      { fr: "4 cm", en: "4 cm" },
    ],
    correctIndex: 0,
    hint: { fr: "L'aire c'est longueur fois largeur : utilise l'opération inverse (division).", en: "Area is length times width: use the opposite operation (division)." },
    strategyId: "a-rebours",
    explanation: { fr: "24 / 4 = 6 cm.", en: "24 / 4 = 6 cm." },
  },
  {
    id: "cha-geo-2",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "La somme des angles d'un triangle fait toujours 180°. Un triangle a deux angles de 70° et 60°. Quel est le troisième angle ?", en: "The angles of a triangle always add up to 180°. A triangle has two angles of 70° and 60°. What is the third angle?" },
    options: [
      { fr: "50°", en: "50°" },
      { fr: "60°", en: "60°" },
      { fr: "40°", en: "40°" },
    ],
    correctIndex: 0,
    hint: { fr: "Additionne les deux angles connus, puis soustrais le total à 180°.", en: "Add the two known angles, then subtract the total from 180°." },
    strategyId: "a-rebours",
    explanation: { fr: "70 + 60 = 130°. 180 - 130 = 50°.", en: "70 + 60 = 130°. 180 - 130 = 50°." },
  },
  {
    id: "cha-geo-3",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Un carré a un périmètre de 20 cm. Quelle est son aire ?", en: "A square has a perimeter of 20 cm. What is its area?" },
    options: [
      { fr: "25 cm²", en: "25 cm²" },
      { fr: "20 cm²", en: "20 cm²" },
      { fr: "16 cm²", en: "16 cm²" },
    ],
    correctIndex: 0,
    hint: { fr: "Trouve d'abord la longueur d'un côté (périmètre divisé par 4), puis calcule l'aire.", en: "First find the length of one side (perimeter divided by 4), then calculate the area." },
    strategyId: "a-rebours",
    explanation: { fr: "20 / 4 = 5 cm de côté. L'aire est 5 x 5 = 25 cm².", en: "20 / 4 = 5 cm per side. The area is 5 x 5 = 25 cm²." },
  },
  {
    id: "cha-geo-4",
    tier: "champion",
    domain: "geometrie",
    prompt: { fr: "Combien de diagonales possède un pentagone (5 côtés) ?", en: "How many diagonals does a pentagon (5 sides) have?" },
    options: [
      { fr: "5", en: "5" },
      { fr: "4", en: "4" },
      { fr: "10", en: "10" },
    ],
    correctIndex: 0,
    hint: { fr: "Depuis chaque sommet, compte les diagonales possibles, puis fais attention à ne pas les compter deux fois.", en: "From each vertex, count the possible diagonals, then be careful not to count them twice." },
    strategyId: "compter-organise",
    explanation: { fr: "Depuis chaque sommet partent 2 diagonales (5 sommets x 2 = 10), mais chaque diagonale est comptée deux fois : 10 / 2 = 5.", en: "From each vertex, 2 diagonals start (5 vertices x 2 = 10), but each diagonal is counted twice: 10 / 2 = 5." },
  },

  // Combinatoire
  {
    id: "cha-com-1",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons différentes peux-tu ranger 4 livres différents sur une étagère ?", en: "How many different ways can you arrange 4 different books on a shelf?" },
    options: [
      { fr: "24", en: "24" },
      { fr: "16", en: "16" },
      { fr: "12", en: "12" },
    ],
    correctIndex: 0,
    hint: { fr: "Pour le premier livre il y a 4 choix, puis 3, puis 2, puis 1 : multiplie ces nombres.", en: "For the first book there are 4 choices, then 3, then 2, then 1: multiply these numbers." },
    strategyId: "essai-organise",
    explanation: { fr: "4 x 3 x 2 x 1 = 24.", en: "4 x 3 x 2 x 1 = 24." },
  },
  {
    id: "cha-com-2",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Dans un groupe de 5 amis, combien de poignées de main différentes peuvent être échangées si chacun serre la main de chaque autre une seule fois ?", en: "In a group of 5 friends, how many different handshakes can happen if everyone shakes each other's hand exactly once?" },
    options: [
      { fr: "10", en: "10" },
      { fr: "20", en: "20" },
      { fr: "5", en: "5" },
    ],
    correctIndex: 0,
    hint: { fr: "Chaque ami serre la main de 4 autres, mais chaque poignée est comptée deux fois : divise par 2.", en: "Each friend shakes 4 other hands, but each handshake gets counted twice: divide by 2." },
    strategyId: "compter-organise",
    explanation: { fr: "5 amis x 4 poignées chacun = 20, mais chaque poignée est comptée deux fois : 20 / 2 = 10.", en: "5 friends x 4 handshakes each = 20, but each handshake is counted twice: 20 / 2 = 10." },
  },
  {
    id: "cha-com-3",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de nombres pairs à 3 chiffres peux-tu former avec les chiffres 1, 2, 3, 4, sans répéter de chiffre ?", en: "How many 3-digit even numbers can you form with the digits 1, 2, 3, 4, without repeating a digit?" },
    options: [
      { fr: "12", en: "12" },
      { fr: "8", en: "8" },
      { fr: "24", en: "24" },
    ],
    correctIndex: 0,
    hint: { fr: "Fixe d'abord le dernier chiffre (il doit être pair : 2 ou 4), puis compte les façons de placer les deux premiers.", en: "First fix the last digit (it must be even: 2 or 4), then count the ways to place the first two." },
    strategyId: "essai-organise",
    explanation: { fr: "Le dernier chiffre a 2 choix possibles (2 ou 4). Pour chacun, il reste 3 chiffres pour les 2 premières places, ce qui donne 3 x 2 = 6 façons. Au total : 2 x 6 = 12.", en: "The last digit has 2 possible choices (2 or 4). For each, 3 digits remain for the first 2 spots, giving 3 x 2 = 6 ways. In total: 2 x 6 = 12." },
  },
  {
    id: "cha-com-4",
    tier: "champion",
    domain: "combinatoire",
    prompt: { fr: "Combien de façons peux-tu choisir 2 fruits parmi 4 fruits différents pour faire une salade de fruits ?", en: "How many ways can you choose 2 fruits out of 4 different fruits to make a fruit salad?" },
    options: [
      { fr: "6", en: "6" },
      { fr: "8", en: "8" },
      { fr: "4", en: "4" },
    ],
    correctIndex: 0,
    hint: { fr: "Liste toutes les paires possibles de façon organisée, sans en compter deux fois.", en: "List all the possible pairs in an organized way, without counting any twice." },
    strategyId: "compter-organise",
    explanation: { fr: "Avec 4 fruits (A, B, C, D), les paires possibles sont AB, AC, AD, BC, BD, CD : cela fait 6 paires.", en: "With 4 fruits (A, B, C, D), the possible pairs are AB, AC, AD, BC, BD, CD: that's 6 pairs." },
  },
];

export function getProblemsForTier(tier: Tier): Problem[] {
  return PROBLEMS.filter((problem) => problem.tier === tier);
}

export function getProblemsForTierAndDomain(tier: Tier, domain: Domain): Problem[] {
  return PROBLEMS.filter((problem) => problem.tier === tier && problem.domain === domain);
}
